#+TITLE: Introduction to Mathematical Thinking: Week-II
#+AUTHOR: Agung Tuanany
#+DATE: 2024-06-02 Sun
#+OPTIONS:
#+STARTUP: Course,
#+TAGS: ossu, math-ossu
#+TOC: headlines 2
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \hypersetup{colorlinks=true, linkcolor=blue, urlcolor=cyan, pdfstartview=FitH}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{ragged2e}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \usepackage{mdframed}
#+LATEX_HEADER: \usepackage{centernot}
#+LATEX_HEADER: \newenvironment{graypar}{\begin{mdframed}[backgroundcolor=gray!20,hidealllines=true,innertopmargin=10pt,innerbottommargin=10pt,innerrightmargin=10pt,innerleftmargin=20pt,skipabove=10pt,skipbelow=10pt]}{\end{mdframed}}

* Lecture-III: Analysis of Language Implication

Our next step in becoming more precise about our use of language for use in mathematics is to take a close look at the
meaning of the word implies[fn:1].

Most of the benefit from understanding the way our language is used in mathematics comes from trying to figure it out.
The benefit in this case is helping to develop your mathematical thinking ability, and extra process of trying to
understand the issue that goes out for you.

In mathematics we frequently encouter expresion:

\begin{center}
\text{\(\phi\) implies \(\psi\)}
\end{center}

 Indeed, implication is the means by which we prove result in mathematics, starting with observations or axioms[fn:2].
So we'd better understand how the word /implies/ behaves.

In particular, how does the truth or falsity of a statement (\(\phi\) implies \(\psi\)), depend on the truth or falsity
of \(\phi\) and \(\psi\)?

Well, the obvious answer is:

\begin{center}
\text{ The truth of \(\phi\), follows from the truth of \(\psi\)}
\end{center}

Let me give you an example,

# \begin{center}
# \text{ \(\phi: \sqrt{2}\) \hspace{2cm} \($\psi: \( 0 < 1\)}
# \end{center}

# Line 69 (or relevant line number)

\begin{center}
\text{ (\(\phi: \sqrt{2}\)) \hspace{2cm} (\(\psi: (0 < 1)\)}
\end{center}


That \(\phi\) of the statement square root of 2 is a rational; and that \(\psi\) of the statement is 0 less than 1. Let's ask
ourselves, is the statement "\(\phi\) implies \(\psi\)" true?

Well, \(\phi\) is TRUE, and we all know that \(\psi\) is true, cause 0 less than 1. So we have both \(\phi\) and \(\psi\) are truth.

Does that mean "\(\phi\) implies \(\psi\)"? Obviously not. There is no relationship between \(\phi\) and \(\psi\).

The \((\psi: \sqrt{2}\)) is take some effort as you see.

And  \((\psi: ( 0 < 1\)) we all know.

So yes, the truth from first statement (\(\phi\)) doesn't follow from truth of (\(\psi)\).

Now, we realize there's complexity with implication that we didn't meet before when we were dealing with "AND", with
"OR", and with "NOT".

Now we know,

\begin{center}
 {\large\textbf{implication involves causality}}
\end{center}

Causality is an issue of great complexity that philosophers have been discussing for generations.

now we're facing a problem. It didn't arise before, because when we're dealing with conjunction (AND) and disjunction
(OR), it didn't matter whether there was any kind of relationship between the two conjuncts or the two disjuncts.

For example, let's look at the sentence:

\begin{center}
\text{{\textbf{1.}} (Julius Caesar is death) \(\land\) \((1 + 1 = 3)\)}

\text{{\textbf{2.}} (Julius Caesar is death) \(\lor\) \((1 + 1 = 3)\)}
\end{center}

Forming a conjunction and disjunction didn't require any kind of relationship between these two sentences. Clearly,
they're independent. One's statement about a long dead individual, and the other one is a mathematical statement.

Let examine above statements:

- Understanding the conjunction Expression:

   1. (Julius Caesar is death) is TRUE

   2. \((1 + 1 = 3)\): is FALSE

So, the conjunction is FALSE.

- Understanding the disjunction Expression:

   1. (Julius Caesar is death) is TRUE.

   2. \((1 + 1 = 3)\): is FALSE

So, the disjunction is TRUE.

The fact that there's no meaningful relationship between the two conjuncts in the first case, or the two disjuncts in
the second case. Created no lull in determining what the truth value was. It was purely in terms of truth and falsity.

But it's no sitting wit implication, because implication involves /causality/.

So let me just express explicitly,

\begin{center}
\text{implication has a truth part and causation part}
\end{center}

What we're going to do? Ignore the /causation/--part. We're going to leave that to the philosophers if you like, and we're
just going to focus on the /truth/--part.

Throwing away a causation, we can't be left with anything useful, but it turns out, it might seem dangerous thing to do,
to throw away this important causation-part implication, but it turns out when we focus on the truth part we left with
enough to save our leaves in mathematics.

So much that we're going to give (truth part) a name,

\begin{center}
\text{(\uline{Julius Caesar is dead}) \(\land\) \((1 + 1 = 3)\)}
\end{center}

We're going to call it *the conditional* or *material conditional*. That's the part we're going to focus on.

So, we're going to split implication into two part:

\begin{center}
\text{implication = \hspace{0.5cm} conditional \hspace{0.5cm} + \hspace{0.5cm} causation}
\end{center}

The first part, the conditional, we're going to define entirely in terms of /*truth value*/. The second part, we're going
to leave to the philosophers.

The symbol that we use normally for *conditional*, at least the symbol I'm going to use, is:

 \begin{equation}
    \implies
 \end{equation}

So I'm going to write conditional expression like this?

\[
 \phi \implies \psi
\]

That's the truth path of \(\phi\) implies \(\psi\).

When we have a conditional expression like above, we call \(\phi\) /*antecedent*/, and we call \(\psi\) the /*consequent*/; And we
going to formally define the truth of \(\phi\) conditional \(\psi\) in terms of the truth of \(\phi\), and the truth of \(\psi\), we
can write like:

\begin{center}
\text{Define the truth of \(\phi \implies \psi\) in terms of the truth | falsity of \(\phi, \psi\)}
\end{center}

Well, you might worry that by throwing away a /causation/, we're going to be left with a notion that's really of no use
whatsoever. That actually is not the case. Even though we're throwing away something of great significance, hanging on
the truth-part leaves us something very useful.

And the reason is, whenever we have a genuine implication, which are actually the only circumstances in which we're
ultimately going to be interested, whenever we have a genuine implication, the truth behavior of the conditional is the
correct one. It really does capture what happens with truth and falsity, when we have genuine implication, we can write
it down:

\begin{center}
\text{When \(\phi\) \uline{does} implies \(\phi\), \(\phi \implies \psi\) behaves "correctly".}
\end{center}

That probably seems a bit mysterious at this stage, but when we start to look at some examples, I think it should become
clear what I mean.

\begin{center}
\text{The advantage is that the conditional is always defined.}
\end{center}

For real implication, you've got that issue of /causation/. the (\(\phi:\sqrt{2}) (\psi: ( 0 < 1\)) example, the truth or
falsity wasn't the issue, it was whether there was a relationship between those two statements. Now, that's a
complicated issue.

But because we're going to define the conditional, purely in terms of the truth value of the two constituents, the
antecedent and the consequent, it turns out that the conditional will always be defined. When we do a genuine
implication, the definition of the conditional will agree with the way implication behaves.

When we don't have a genuine implication, the conditional will still be defined, and so we can proceed.

Again, this probably seems very mysterious when I describe it in this way. But as we develop some examples, I hope
you'll be able to understand what I'm trying to get at.

Let me take a quiz:

\begin{center}
The truth of the conditional \(\phi \implies \psi\) is defined in terms of
\vspace{1em}
\begin{tabular}{l}
    [ ] The truth of \(\phi\) and \(\psi\) \\[1em]
    [ ] Whether \(\phi\) causes \(\psi\)  \\[1em]
    [ ] Both
\end{tabular}
\end{center}

Which is it?

It's number 1.

We define the truth of a conditional in terms of the truth and falsity of the antecedents and the consequent; And
because we define the truth of the conditional in terms of truth and falsity in that way, it has a truth table.


    |---+---------------------+--------------------+-----------------------------------+---|
    |   |         <c>         |        <c>         |                <c>                |   |
    |   | \(\phi\) (Conditional) | \(\psi\) (Conclusion) | \(\phi \implies  \psi\)   (Implication) |   |
    |---+---------------------+--------------------+-----------------------------------+---|
    | / |          <          |         <          |                 <                 | > |
    |   |          T          |         T          |                 ?                 |   |
    |---+---------------------+--------------------+-----------------------------------+---|
    |   |          T          |         F          |                 ?                 |   |
    |---+---------------------+--------------------+-----------------------------------+---|
    |   |          F          |         F          |                 ?                 |   |
    |---+---------------------+--------------------+-----------------------------------+---|
    |   |          F          |         F          |                 ?                 |   |
    |---+---------------------+--------------------+-----------------------------------+---|

** Fill the First Table

This part We've already looked at.

    |---+---------------------+--------------------+-----------------------------------+---|
    |   |         <c>         |        <c>         |                <c>                |   |
    |   | \(\phi\) (Conditional) | \(\psi\) (Conclusion) | \(\phi \implies  \psi\)   (Implication) |   |
    |---+---------------------+--------------------+-----------------------------------+---|
    | / |          <          |         <          |                 <                 | > |
    |   |          T          |         T          |                 T                 |   |
    |---+---------------------+--------------------+-----------------------------------+---|

We define the conditional (\(\phi\)) as the truth part of implication; And implication has a property that a true
implication leads to a true conclusion (\(\psi\)) from a true assumption.

So because we take the conditional from real implication, we have truths all the way throughout the top level.

#+begin_export latex
\begin{graypar}
#+end_export

NOTE:

Lets break down the definition of implication and how it works with logical statements, so it makes sense in the
contexts.

*Understanding implication (\(\implies \))*

1. *Conditional (\phi)*: This is the "IF" part of the statement.

2. *Conclusion (\psi)*: This is the "THEN" part of the statement.

In logic, the implication (\(\phi \implies \psi\)) read as "IF \(\phi\), then \(\psi\)", this means:

- When \(\psi\) (the condition) is TRUE, \(\phi\) (the conclusion) must be TRUE for the entire statement to be true.

- If \(\phi\) is TRUE and \(\psi\) is FALSE, the implication is FALSE.

- If \(phi\) is FALSE, the implication is TRUE regardless of the truth value of \(\psi\).

*Truth Table for Implication*

Here's how we can visualize this truth table:

|---+---------------------+--------------------+-----------------------------------+---|
|   |         <c>         |        <c>         |                <c>                |   |
|   | \(\phi\) (Conditional) | \(\psi\) (Conclusion) | \(\phi \implies  \psi\)   (Implication) |   |
|---+---------------------+--------------------+-----------------------------------+---|
| / |          <          |         <          |                 <                 | > |
|   |          T          |         T          |                 T                 |   |
|---+---------------------+--------------------+-----------------------------------+---|
|   |          T          |         F          |                 F                 |   |
|---+---------------------+--------------------+-----------------------------------+---|
|   |          F          |         T          |                 T                 |   |
|---+---------------------+--------------------+-----------------------------------+---|
|   |          F          |         F          |                 T                 |   |
|---+---------------------+--------------------+-----------------------------------+---|

*Explanation in Simple Terms*

- If both the condition (\(\phi\)) and the conclusion (\(\psi\)) are true, the implication is true.

- If the condition (\(\phi\)) is true and the conclusion (\(\psi\)) is false, the implication is false. This because the truth
  of the condition did not lead a true conclusion.

- If the condition (\(\phi\)) is false, the implication is always true, regardless of whether the conclusion (\(\psi\)) is
  true or false. This might seem counterintuitive, but it's because an implication with a false condition doesn't make
  any promise about the conclusion.

*Putting it All Together*

*Statement*: "We define the conditional (\(\phi\)) as the truth part of implication; and implication has a property that a true implication leads
to a true conclusion (\(\psi\)) from a true assumption."

This means:

- The conditional (\(\phi\)) is the part we assume or check first.

- The implication (\(\phi \implies \psi\)) says that if our assumption (\(\phi\)) is true, then the conclusion (\(\psi\)) must also
  be true.

- If our assumption (\(\phi\)) is true and leads to a true conclusion(\(\psi\)), then the implication (\(\phi \implies \psi\)) is
  true.

- If our assumption (\(\phi\)) is false, we don't care about the conclusion (\(\psi\)); the implication (\(\phi \implies \psi\)) is
  considered true by default.

*Simplified Example*

Consider the statement "If it rains (\(\phi\)), then the ground will be wet (\(\psi\))."

- If it rains and ground is wet, the implication is true.

- If it rains and ground is not we, the implication is false.

- If it doesn't rain, the implication is true regardless of whether the ground is wet or not.

#+begin_export latex
\end{graypar}
#+end_export

Let's look at the first row of the truth table above, and I give you some example to observe:

\begin{center}
\text{\((\phi: N > 7) \hspace{1.5cm} (\psi: N^2 > 40)\)}

\text{This is consistent with the truth table.}
\end{center}

Suppose \(\phi\) is the statement (\(N > 87\)); And suppose \(\psi\) is the statement (\(N^2 > 40\)). In other words

  - If \(N\) is bigger than 7, then \(N^2\) is bigger than 40.

In fact, it's bigger than 40 now. So, certainly, in this case \(\phi\) implies \(psi\) or it is TRUE.

Now let's look at different example.

\begin{center}
\text{(Julius Caesar is death) \hspace{1.5cm} \((\pi > 3)\)}

\end{center}

\(\phi\) is true,  \(\psi\) is true, According to the truth table, it follows that

\begin{center}
\text{\(\phi \implies \psi\)}
\end{center}

In other words,

\begin{center}
\text{(Julius Caesar is death) \(\implies\) \((\pi > 3)\)}
\end{center}

Now, if you read this as Julius Caesar is dead implies pi bigger than 3, then you're in a nonsensical situation. But
remember above statement isn't implication, this is just truth part implication, and in terms of the truth part there's
no problem.

In the first example, (\((\phi: N > 7) (\psi: N^2 > 40)\)) there is meaningful relationship between \(\phi\) and \(\psi\).

When we know that \(N\) is bigger than 7, than we can conclude that \(N^2\) is certainly bigger than 40. There's
connection between the two statement (condition and conclusion); And in this case, the behavior of the conditional is
certainly consistent with what's really going on.

In the second example, there's no connection between the two.

The conditional is true, but it's got nothing to do with one thing following from the other.

The value of doing this (in the second example), is even though has no meaning in terms of implication, its truth value
is defined.

In both cases, we have a well-defined truth value. In the first case, it's a meaningful truth value. In the second case,
it's purely defined truth value.

But that's not going to cause us any problem, because we're never going to encouter like second case in mathematics. We
encounter the first case all the time.

So all we've done is we've extended a notion to be defined under all circumstances; And we've done it in a way that's
consistent with the behavior we want when something meaningful is going on.

This is actually quite common in mathematics to extend the domain of definition of something so that it's always defined.

So long as it has the correct behavior, the correct definition for the meaningful cases, and provided we do the
definition correctly, it really doesn't cause any problems. In fact, it solves a lot of problems and eliminates a lot of
difficulties. If we extend the definition so that it covers all cases.

Is it just something we do in mathematics all the time? May seem strange when you first meet it, but it is a part of
modern advanced mathematics. Incidentally, if you think is just playing games, let me mention that the computer system
that controls that aircraft that you'll be flying in next time depends upon the fact that expressions like (\(\phi \implies
\psi\)) are always well defined.

But software control system doesn't depend upon knowing "Julius Caesar is death" or things like that. It doesn't depend
on those kind of facts of the world.

Computer systems, by and large, don't depend upon understanding causation, which is just as well, because they don't.

What computer systems depends upon is that things are always accurately and precisesly defined.

And this expression, (\(\phi \implies \psi\)) occurs all over the places in software systems. So, quite literally, your life
depends upon the fact that this is always well-defined. It doesn't depend upon the fact that the computer doesn't know
whether "Julius Caesar is death."

** Fill the second table

Okay, time to look at the second table,

    |---+---------------------+--------------------+-----------------------------------+---|
    |   |         <c>         |        <c>         |                <c>                |   |
    |   | \(\phi\) (Conditional) | \(\psi\) (Conclusion) | \(\phi \implies  \psi\)   (Implication) |   |
    |---+---------------------+--------------------+-----------------------------------+---|
    | / |          <          |         <          |                 <                 | > |
    |   |          T          |         F          |                 ?                 |   |
    |---+---------------------+--------------------+-----------------------------------+---|

What will the value on (\(\phi \implies \psi\)), if \(\phi\) is true, and \(\psi\) is false?

When we think about it in terms of genuine implication, because we trying to capture the truth behavior with genuine
implication.

So if it was the case that (\(\phi \implies \psi\), if that statement was true when we interpret it as real implication, Then
the truth of \(\psi\) would follow from the truth of \(\psi\). That's how we began remember.

That's real implication means, the truth of \(\psi\) will follow from truth from \(\phi\).

So, if the result of implication is TRUE, then when we have a TRUE of \(\phi\), we would have TRUE in \(\psi\). But we don't.
We've got FALSE in \(\psi\). So, we cannot have a TRUE value in implication \(\phi\) of \(\psi\), because if we put TRUE as a
result, the conditional is contrary, it contradicts real implication and we're trying to extend implication to be
defined in all cases where there's no causation.

So it has to be FALSE.

    |---+---------------------+--------------------+---------------------------------+---|
    |   |         <c>         |        <c>         |               <c>               |   |
    |   | \(\phi\) (Conditional) | \(\psi\) (Conclusion) | \(\phi \implies  \psi\) (Implication) |   |
    |---+---------------------+--------------------+---------------------------------+---|
    | / |          <          |         <          |                <                | > |
    |   |          T          |         F          |                F                |   |
    |---+---------------------+--------------------+---------------------------------+---|

In order that the conditional agrees with real implication, that has to be an FALSE. If it's a truth, then we would have
true antecedent and false consequence from a true implication.

Let me write that down just to make sure everyone's following what I'm trying to say.

\begin{quote}
If there were a genuine implication "\(\phi\) implies \(\psi\), and if that implication were TRUE then \(\psi\) would have to be
TRUE if \(\phi\) were TRUE.

So we cannot have \(\phi\) TRUE and \(\psi\) FALSE if \(\phi \implies \psi\) is TRUE
\end{quote}

That means, that in the case where \(\phi\) is true and \(\psi\) is false we have a false implication.

** Fill the last two table

    |---+---------------------+--------------------+---------------------------------+---|
    |   |         <c>         |        <c>         |               <c>               |   |
    |   | \(\phi\) (Conditional) | \(\psi\) (Conclusion) | \(\phi \implies  \psi\) (Implication) |   |
    |---+---------------------+--------------------+---------------------------------+---|
    | / |          <          |         <          |                <                | > |
    |   |          F          |         T          |                ?                |   |
    |   |          F          |         F          |                ?                |   |
    |---+---------------------+--------------------+---------------------------------+---|

Now if you're like me, you have no intuitions as to what to put above; And the reason you have no intuition is that
even though you're used to dealing with implication you've never dealt with an implication where the antecedent
(conditional) was false. You're only ever interested in drawing conclusions from true assumptions.

You do have an intuition with:

 \begin{center}
 \text{\(\phi \centernot\implies \psi\)}
 \end{center}

The reason that's going to help us out, that negation implication (\(\centernot\implies\)) swap around falsity of
\(\phi\). So corresponding to the "F" for \(\phi\) here when we look at \(\phi\) on (\(\phi \centernot\implies \psi\)) we'll have
truths.

So you are used to having deal with (\(\phi \centernot\implies \psi\)),

So The trick, or at least the idea by which we're going to figure out what goes here, is to stop looking at implication
(\(\implies\)) and look at (\(\centernot\implies\)). \(\phi\) does not imply \(\psi\) if even though \(\phi\) is true, \(\psi\)
neverthenless false.

That's how you know that (\(\phi \centernot\implies \psi\)) holds. You know that \(\phi\) doesn't imply \(\psi\) if you can check
\(\phi\) is true but \(\psi\) neverthenless false.

    |---+---------------------+--------------------+------------------------------------------+---|
    |   |         <c>         |        <c>         |                   <c>                    |   |
    |   | \(\phi\) (Conditional) | \(\psi\) (Conclusion) | \(\phi \centernot\implies \psi\) (Implication) |   |
    |---+---------------------+--------------------+------------------------------------------+---|
    | / |          <          |         <          |                    <                     | > |
    |   |          T          |         F          |                    T                     |   |
    |---+---------------------+--------------------+------------------------------------------+---|

That's the how you now that (\(\phi \centernot\implies \psi\)) holds, you know that \(\phi\) doesn't imply \(\psi\) if you can check
that \(\phi\) is true but \(\psi\) is false.

That's the only circumstance under which you can conclude (\(\centernot\implies\)) is true. In all other circumstances
(\(\phi \centernot\implies \psi\)) will be false.

Let me write a conclusions:

 \begin{center}
 \text{In all other circumstances \(\phi \centernot\implies \psi\) will be false}

 \text{In all other circumstances \(\phi \implies \psi\) will be true}
 \end{center}

Because \((\neg)\) swap false and true, \(\phi \centernot\implies \psi\) will be false, and \(\phi \implies \psi\) will be true

Let me give you a little quiz?

\begin{center}
\text{Which of the following are true?}

\text{\(\phi \implies \psi\) is true, whenever:}

\vspace{1em}
\begin{tabular}{l}
   [ ] \(\phi\) and \(\psi\) are both true \\[1em]
   [ ] \(\phi\) is false and \(\psi\) is true \\[1em]
   [ ] \(\phi\) and \(\psi\) are both false \\[1em]
   [ ] \(\phi\) is true and \(\psi\) is false \\[2em]
\end{tabular}

\text{check all that are true!!}
\end{center}

Which of these four conditions all the case when \(\phi \implies \psi\) is true?

The answer is 1, 2, and 3.

** Summary

We've defined a notion, the conditional, that captures only part of what implies means.

To avoid difficulties, we base our definition solely on the notion of truth and falsity. Our definition agrees with our
intuition concerning implication in all meaningful cases.

The definition for a true anticedent is based on analysis of the truth values of genuine implication.

The definition for false antecedent, is based n a truth value analysis of the notion does not imply.

In defining the conditional the way we do, we do not end up with a notion that contradicts a notion of genuine
implication.

Rather, we obtain a notion that extends genuine implication to cover those cases where the claim of implication is
irrelevant, because the antecedent is false or meaningless when there's no real connection between the antecedent and
the consequences.

In the meaningful case where there is a relationship between \(\phi\) and \(\psi\), and in addition, where \(\phi\) is true,
namely, the cases covered by the first two rows of the truth table, the truth value of the conditional will be the same
as the truth value of the actual implication.

Remember, it's the fact that the conditional always has a well-defined truth value that makes this notion important in
mathematics since in mathematics, we can't afford to have statements with undefined truth values floating around.

I've kept assignment three fairly short since I expect you'll need most of your time simply understanding our analysis
of implication and the definition of the conditional.

** Last Quiz

Here the last quiz:

Here the last quiz:

\begin{center}
\text{If the conditional is true, check the corresponding box.}

\vspace{1em}
\begin{tabular}{l}
   [ ] \((\pi^2 > 2) \implies (\pi > 1.2)\) \\[1em]
   [ ] \((\pi^2 < 0) \implies (\pi = 3)\) \\[1em]
   [ ] \((\pi^2 > 0) \implies (1 + 2 = 3)\) \\[1em]
   [ ] (The area of a circle of radius is \(\pi\)) \(\implies\) (3 is prime) \\[1em]
   [ ] (Triangles have four sides) \(\implies\) (Squares have five sides) \\[1em]
   [ ] (Euclid's brithday was july 4) \(\implies\) (Rectangles have four sides) \\ [2em]
\end{tabular}
\end{center}

|---+---------------+---------------+-------------------------------------+---|
|   |      <c>      |      <c>      |                 <c>                 |   |
|   | \((\pi^2 > 0)\) | \((\pi > 1.2)\) | \((\pi^2 > 0 ) \p\implies (\pi > 1.2)\) |   |
|---+---------------+---------------+-------------------------------------+---|
| / |       <       |       <       |                  <                  | > |
|   |       T       |       T       |                  T                  |   |
|---+---------------+---------------+-------------------------------------+---|

The answer for the first one is that it's TRUE. The antecedent \((\pi^2 > 2)\) is true and the consequence is true, so the
conditional is true.

In fact there's deeper result is going on the first one. Providing you take a positive number, instead of \(\pi\), any
positive number, then if the \(N^2\) of that positive number bigger than 2, that number must be bigger than 1.2. Because
the \(2^2 = 1.41421356237\).

So for positive numbers, it doesn't have to be \((\pi)\) it can be anything. Any positive number whose square is bigger
than 2, it must be bigger than 1.2.

The first question would be a case of genuine causation and genuine implication. But in terms of the conditional, it's
enough that the antecedent its true, then the consequence is true.

|---+---------------+-------------+----------------------------+---|
|   |      <c>      |     <c>     |            <c>             |   |
|   | \((\pi^2 < 0)\) | \((\pi = 3)\) | \((\pi^2) \implies (\pi = 3)\) |   |
|---+---------------+-------------+----------------------------+---|
| / |       <       |      <      |             <              | > |
|   |       F       |      F      |             T              |   |
|---+---------------+-------------+----------------------------+---|

For the second question it's also TRUE. Now the consequence is false \((\pi = 3)\) but the antecedent is false \((\pi^2 <
0)\); And if you have false antecedent, the conditional is always true. \(\pi^2\) is most certainly not less than 0. So
you've got \((\pi^2 < 0)\) is false, \((\pi = 3)\) is false, that makes the conditional true.

|---+---------------+-----------------+-------------------------------+---|
|   |      <c>      |       <c>       |              <c>              |   |
|   | \((\pi^2 > 0)\) | \((1 + 2 = 3)\) | \((\pi^2) \implies (1 + 2 =3)\) |   |
|---+---------------+-----------------+-------------------------------+---|
| / |       <       |        <        |               <               | > |
|   |       T       |        F        |               F               |   |
|---+---------------+-----------------+-------------------------------+---|

Number three, that's one false. The antecedent is true, and the consequence is false; And you cannot obtain a false
conclusion from a true assumption.

|---+--------------------------+--------------+----------------------------------------------------+---|
|   |           <c>            |     <c>      |                        <c>                         |   |
|   | (circle radius is \(\pi\)) | (3 is prime) | (circle radius is \(\pi\)) \(\implies\) (3 is prime) |   |
|---+--------------------------+--------------+----------------------------------------------------+---|
| / |            <             |      <       |                         <                          | > |
|   |            T             |      T       |                         T                          |   |
|---+--------------------------+--------------+----------------------------------------------------+---|

The forth is true. The antecedent is true, and the consequence is true.

|---+-----------------------+---------------------+--------------------------------------------------------+---|
|   |          <c>          |         <c>         |                          <c>                           |   |
|   | (Triangles = 4 sides) | (Squares = 5 sides) | (Triangles = 4 sides) \(\implies\) (Squares = 5 sides) |   |
|---+-----------------------+---------------------+--------------------------------------------------------+---|
| / |           <           |          <          |                           <                            | > |
|   |           F           |          F          |                           T                            |   |
|---+-----------------------+---------------------+--------------------------------------------------------+---|

Do triangles have four sides? No. Do squares have five sides? No. But anything with a false antecedent is true, so
that's true.

You've got conditional false, conclusion false, so that's true.

|---+---------------------+------------------------+---------------------------------------------------------+---|
|   |         <c>         |          <c>           |                           <c>                           |   |
|   | (Euclid's = july 4) | (Rectangles = 4 sides) | (Euclid's = july 4) \(\implies\) (Rectangles = 4 sides) |   |
|---+---------------------+------------------------+---------------------------------------------------------+---|
| / |          <          |           <            |                            <                            | > |
|   |          T          |           T            |                            T                            |   |
|   |          F          |           T            |                            T                            |   |
|---+---------------------+------------------------+---------------------------------------------------------+---|

We don't know Euclid's birthday was. At least, I don't know when Euclid's birthday was. I suspect you either.

Either the consequences is true, or it's false.

Either way, since the consequence is true, the thing is true.

We've going to run down /using two consequences/, so either we have true consequence and true conclusion, in which case,
it's true; or we have false consequence and true conclusion, in which case, it's true.

* Assignment-3 for Lecture-III
** Q: Let /D/ be the statement "The dollar is strong", /Y/ the statement "The yuan is strong", and /T/ statement "New US-China trade agreement signed". Express the main content of each of the following (fictitious) newspaper headlines in logical notation.

Remember, logical notation captures truth, but not the many nuances and inferences of natural language. As before, make sure you could justify and defend your answer.

1. New trade agreement will leas to strong currencies in both countries.

2. Strong Dollar means a weak Yuan

3. Trade agreement fails on news of weak Dollar.

4. If new trade agreement is signed. Dollar and Yuan can't both remain strongly

5. Dollar weak but Yuan strong. Following new trade agreement.

6. If the trade agreement is signed, a rise in the Yuan will result in a fall in the Dollar.

7. New trade agreement means Dollar and Yuan will rise and fall together.

8. New trade agreement will be good for one side. But no one knows which


*A*:

Let's start by converting each of the statement into logical notation. Then we will create a truth table to illustrate
the possible truth values.

1. New trade agreement will leas to strong currencies in both countries.

   - Logical notation: \(T \implies (D \land Y)\)

2. Strong Dollar means a weak Yuan

   - Logical notation: \(D \implies \neg Y\)

3. Trade agreement fails on news of weak Dollar.

   - Logical notation: \(\neg D \implies \neg D\)

4. If new trade agreement is signed. Dollar and Yuan can't both remain strongly

   - Logical notation: \(T \implies \neg (D \land T)\)

5. Dollar weak but Yuan strong. Following new trade agreement.

   - Logical notation: \(T \implies (\neg D \land T)\) or (\(\neg D \land Y \land T))

6. If the trade agreement is signed, a rise in the Yuan will result in a fall in the Dollar.

   - Logical notation: \(T \implies [Y \implies \neg D]\) or \((T \land Y) \implies \neg D \)

7. New trade agreement means Dollar and Yuan will rise and fall together.

   - Logical notation:

     - \(T \implies (Y \iff \neg D)\) or

     - \(T \implies [(D \implies Y) \land (Y \implies D)]\)

8. New trade agreement will be good for one side. But no one knows which

   - Logical notation:

     - \(T \implies (D \oplus Y)\)

     - \(T \implies [(D \lor Y) \land \neg (D \land Y)]\)

** Q: Complete the following truth table

|---+-------+---------+-------+------------------+-------------+---|
|   |  <c>  |   <c>   |  <c>  |       <c>        |     <c>     |   |
|   | \(\phi\) | \(\neg \phi\) | \(\psi\) | \(\phi \implies \psi\) | \(\neg \phi \lor \psi\) |   |
|---+-------+---------+-------+------------------+-------------+---|
| / |   <   |    <    |   <   |        <         |      <      | > |
|   |   T   |    ?    |   T   |        ?         |      ?      |   |
|   |   T   |    ?    |   F   |        ?         |      ?      |   |
|   |   F   |    ?    |   T   |        ?         |      ?      |   |
|   |   F   |    ?    |   F   |        ?         |      ?      |   |
|---+-------+---------+-------+------------------+-------------+---|

Note: \((\neg)\) has the same binding rules as \((-)\) (minus) in arithmetic and algebra, so \(\neg \phi \lor \psi\) is the same as
\((\neg \phi) \lor \psi\)

*A*:

|---+-------+---------+-------+------------------+-------------+---|
|   |  <c>  |   <c>   |  <c>  |       <c>        |     <c>     |   |
|   | \(\phi\) | \(\neg \phi\) | \(\psi\) | \(\phi \implies \psi\) | \(\neg \phi \lor \psi\) |   |
|---+-------+---------+-------+------------------+-------------+---|
| / |   <   |    <    |   <   |        <         |      <      | > |
|   |   T   |    F    |   T   |        T         |      T      |   |
|   |   T   |    F    |   F   |        F         |      F      |   |
|   |   F   |    T    |   T   |        T         |      T      |   |
|   |   F   |    T    |   F   |        T         |      T      |   |
|---+-------+---------+-------+------------------+-------------+---|

*Explanation*:

1. First row (\(\phi = T, \psi = T\))

   -  \(\neg \phi\) = F

   - \(\phi \implies \psi = T \implies T = T\)

        1. When \(\phi = T\) and \(\phi = T\):

           - Statement: \(\phi \implies \psi\)

           - Substitution: \(T \implies T\)

           - Evaluation:

             - According to the truth table, if both \(\phi\) and \(\psi\) are true, then the implication \(\phi \implies \psi\) is true.

             - Therefore, \(T \implies T\) evaluates to \(T\).

        So, \(T \implies T = T\) evaluates to \(T\)

   - \(\neg \phi \lor \psi = F \lor T = T\)

2. Second row (\(\phi = T, \psi = F)\)

   - \(\neg \phi = F\)

   - \(\phi \implies \psi = T \implies F = F\)

   - \(\neg \phi \lor \psi = F \lor F = F)

3. Third row (\(\phi = F, \psi = T)\)

   - \(\neg \phi = T\)

   - \(\phi \implies \psi = F \implies T = T\)

   - \(\neg \phi \lor \psi = T \lor T = T)

4. Fourth row (\(\phi = F, \psi = F)\)

   - \(\neg \phi = T\)

   - \(\phi \implies \psi = F \implies F = T\)

   - \(\neg \phi \lor \psi = T \lor F = T)

** Q: What conclusion can you draw from the above table?

From the truth table, we can observer the following:

- The expression \(\phi \implies \psi\) and \(\neg\phi \lor \psi\) have identical truth value in all cases.

- This demonstrates that \(\phi \implies \psi\) is logical equivalent to \(\neg\phi \lor \psi\). This is a fundamental equivalence in
  propositional logic known as the implication equivalence.

- \(\phi \implies \psi) \iff (\neg\phi \lor \psi)\)

** Q: Complete the following truth table.

Recall that \((\phi \centernot\implies \psi)\) is another way of writing \((\neg [\phi \implies \psi])\).

|---+-------+-------+---------+------------------+----------------------------+-------------+---|
|   |  <c>  |  <c>  |   <c>   |       <c>        |            <c>             |     <c>     |   |
|   | \(\phi\) | \(\psi\) | \(\neg \phi\) | \(\phi \implies \psi\) | \(\phi \centernot\implies \psi\) | \(\phi \land \neg \psi\) |   |
|---+-------+-------+---------+------------------+----------------------------+-------------+---|
| / |   <   |   <   |    <    |        <         |             <              |      <      | > |
|   |   T   |   T   |    ?    |        ?         |             ?              |      ?      |   |
|   |   T   |   F   |    ?    |        ?         |             ?              |      ?      |   |
|   |   F   |   T   |    ?    |        ?         |             ?              |      ?      |   |
|   |   F   |   F   |    ?    |        ?         |             ?              |      ?      |   |
|---+-------+-------+---------+------------------+----------------------------+-------------+---|

*A*:

My first attempt:

|---+-------+-------+---------+------------------+----------------------------+-------------+---|
|   |  <c>  |  <c>  |   <c>   |       <c>        |            <c>             |     <c>     |   |
|   | \(\phi\) | \(\psi\) | \(\neg \phi\) | \(\phi \implies \psi\) | \(\phi \centernot\implies \psi\) | \(\phi \land \neg \psi\) |   |
|---+-------+-------+---------+------------------+----------------------------+-------------+---|
| / |   <   |   <   |    <    |        <         |             <              |      <      | > |
|   |   T   |   T   |    F    |        T         |             F              |      F      |   |
|   |   T   |   F   |    T    |        F         |             T              |      T      |   |
|   |   F   |   T   |    T    |        T         |             T              |      T      |   |
|   |   F   |   F   |    T    |        T         |             T              |      F      |   |
|---+-------+-------+---------+------------------+----------------------------+-------------+---|

(This have incorrect answers, take a look at below table.)

My second attempt:

|---+-------+-------+-----------------------------+---|
|   |  <c>  |  <c>  |             <c>             |   |
|   | \(\phi\) | \(\psi\) | \(\phi \centernot\implies  \psi\) |   |
|---+-------+-------+-----------------------------+---|
| / |   <   |   <   |              <              | > |
|   |   T   |   T   |              F              |   |
|   |   T   |   F   |              T              |   |
|   |   F   |   T   |              F              |   |
|   |   F   |   F   |              F              |   |
|---+-------+-------+-----------------------------+---|

- I have to fix the negation of the implication (\(\phi\) does not imply \(\psi\))
|---+-------+-------+---------+------------------+----------------------------+-------------+---|
|   |  <c>  |  <c>  |   <c>   |       <c>        |            <c>             |     <c>     |   |
|   | \(\phi\) | \(\psi\) | \(\neg \phi\) | \(\phi \implies \psi\) | \(\phi \centernot\implies \psi\) | \(\phi \land \neg \psi\) |   |
|---+-------+-------+---------+------------------+----------------------------+-------------+---|
| / |   <   |   <   |    <    |        <         |             <              |      <      | > |
|   |   T   |   T   |    F    |        T         |             F              |      F      |   |
|   |   T   |   F   |    F    |        F         |             T              |      T      |   |
|   |   F   |   T   |    T    |        T         |             F              |      F      |   |
|   |   F   |   F   |    T    |        T         |             F              |      F      |   |
|---+-------+-------+---------+------------------+----------------------------+-------------+---|

* Lecture-IV: Analysis of Language Equivalent

This lecture's going to be fairly short as well. The next topic I want to look at is logical equivalence[fn:3].

Equivalence is closely related to implication. Two statements are said to be equivalent, or more fully, logically
equivalent, if each implies the other. Equivalence is a central notion in mathematics.

Many mathematical result are proofs that two statement are equivalent. In fact, equivalence is to logic as equations are
to arithmetic and algebra; And you already know that equations play a central role in mathematics.

Just as we had introduce a formal version implication that avoids the complex issue of causation, namely the
conditional. We have to introduce an analogous version of equivalence. It called "Biconditional". Fortunately, we did
all the difficult work with implication. Now we can reap the benefits of those efforts.

Two statement \(\Phi\) and \(\Psi\) area said to be (logically) equivalent, or just equivalent if each implies the other we
call it the biconditional.

The biconditional of \(\phi\) and \(\psi\) is denoted by "\(\iff\)".

\begin{center}
    \(\iff\)
\end{center}

Formally, the biconditional is an abbreviation of:

\begin{center}
   \((\phi \implies \psi) \land (\psi \implies \phi)\)
\end{center}

Since the conditional is defined it terms of truth values, it follows that biconditional is defined in terms of truth
values.

If you work out the truth table for \(\phi\) conditional \(\psi\) (\(\phi \implies \psi\)) and \(\psi\) conditional \(\phi\) (\(\psi
\implies \phi\)) then you work out the conjunction, you'll get the truth table for (\(\phi \iff \psi\))

If you that, what you will find is that \(\phi \iff \psi\) is true, if \(\phi\) and \(\psi\) are both true or both false.


One way to show two statements \(\Phi\), \(\Psi\) are equivalent is to show they have the same truth table.

Actually to avoid confusion, I choose to use capital phi (\(\Phi\)) and capital psi (\(\Psi\)), because I want to use
the lower case phi (\(\phi\)) and psi (\(\psi\)) for something else.

For example,

\begin{center}
  \text{(i)\uline{\((\phi \land \psi) \lor (\neg \psi)\)} is equivalent to (ii)\uline{\(\phi \implies \psi\)}}

  \text{(i) = \(\Phi\), (ii) = \(\Psi\) }
\end{center}

If I was teaching this material at high school level, I'd be very careful to choose different letters to denote
everything, but we're looking at college, university level mathematics now; And university mathematicians, professional
mathematicians frequently use upper case and lower case symbol in the same context; And part of being able to master
university level is actually getting use to disambiguous notations.

What we have to do is to work up truth table for \(\Phi\) and truth table for \(\Psi\).

|---+-------+-------+-----------+--------+---------------------+------------------+---|
|   |  <c>  |  <c>  |    <c>    |  <c>   |         <c>         |       <c>        |   |
|   | \(\phi\) | \(\psi\) | \(\phi \land \phi\) | \(\neg\phi\) | \((\phi \land \psi) \lor (\neg\phi)\) | \(\phi \implies \psi\) |   |
|---+-------+-------+-----------+--------+---------------------+------------------+---|
| / |   <   |   <   |     <     |   <    |          <          |        <         | > |
|   |   T   |   T   |     T     |   F    |          T          |        T         |   |
|   |   T   |   F   |     F     |   F    |          F          |        F         |   |
|   |   F   |   T   |     F     |   T    |          T          |        T         |   |
|   |   F   |   F   |     T     |   T    |          T          |        T         |   |
|---+-------+-------+-----------+--------+---------------------+------------------+---|


You can check the last two table above, it's the same.

I should mention that provind equivalence by means of truth tables is very unusual. It's only special case of
equivalence.

In general proving equivalence is really quite hard. You have to look at what the two statements mean and develop a
proof based on their meaning.

Equivalence itself is not too difficult to notion deal with. What is problematic is mastering the various nomenclatures
that are associated with implication.

** Expression \(\phi \implies \psi\)

There are many different expression we use to describe "\(\phi \implies \psi\)", some of them intuitively obvious and some of them
are actually counter-intuitive when you first meet them.

NOTE:
\begin{center}
 \text{\(\phi \implies \psi\)}

 \text{\(\phi\): antecedent} \\
 \text{\(\psi\): consequent}
\end{center}

The following all mean "\(\phi \implies \psi\)":

*** If \(\phi\), the \(\psi\)

This is the most straightforward way to express an implication, it means that whenever \(\phi\) is true, \(\psi\) must also
true.

*Example*:
  - \(\phi\): It is raining.
  - \(\psi\): The ground is wet.
  - Statement: If it is raining, the ground is wet.

*** \(\phi\) is sufficient for \(\psi\)

   This mean that \(\phi\) being true guarantees that \(\psi\) is true. If \(\phi\) happens, \(\psi\) must also happen.

   *Example*:
    - \(\phi\): You get 90% or more on a test.
    - \(\psi\): You pass the test.
    - Statement: Getting 90% or more on a test is sufficient for passign the test.

   If you score 90% or more, you will definitely pass.

*** \(\phi\) only if \(\psi\)  [NOT SAME as "IF \(\psi\) THEN \(\psi\)"]

Let's clarify the difference between "\(\phi\) only if \(\psi\)" and "if \(\psi\), then \(\phi\)". These statement might sound
similar, but they different meanings in logic.

1. "\(\phi\) only if \(\psi\)":

   - This statement means that \(\psi\) true only if \(\psi\) is also true.

   - In logical terms, \(\phi\) only if \(\psi\) written as: \(\phi \implies \psi\).

2. "If \(\psi\), then  \(\phi\)":

   - This statement means that if \(\psi\) is true, then \(\phi\) must also be true.

   - In logical terms, if \(\psi\), then \(\phi\) is written as: \(\psi \implies \phi\)

*Difference*:

Let look at each statement more closely:

- *"\(\phi\) only if \(\psi\)"* (\(\phi \implies \psi\))

  - This means that whenever \(\phi\) is true, \(\psi\) must also true.

  - If \(\psi\) false, then \(\phi\) also be false.

  - This does *not* necessarily mean that \(\psi\) being true implies that \(\phi\) is true.

- *"if \(\psi\), then \(\phi\)"* (\(\psi \implies \phi\))

  - This means that whenever \(\psi\) is true, \(\phi\) must also be true.

  - If \(\phi\) false, then \(\psi\) must also be false.

  - This does *not* necessarily means that \(\phi\) being true implies that \(\psi\) is true.

*Example*:

*A.* Consider the statements:

  - \(\phi\): "It is raining."
  - \(\psi\): "The ground is wet."

*"\(\phi\) only if \(\psi\)"* means "It is raining only if ground is wet" (\(\phi \implies \psi\))

  - This means: If it is raining, then the ground must be wet.

  - It does *not* mean: If the ground is wet, then it is raining. (The ground could be wet for other reasons, such as
    someone watering the garden.)

*"if \(\psi\), then \(\phi\)"* means "If the ground is wet, then it is raining" (\(\psi \implies \phi\))

  - This means: If ground is wet, then it is raining.

  - It does *not* mean: If it raining, then ground is wet. (The ground being wet is a consequence of rain, but rain can
    occur without the ground getting wet if, for instance, it is raining in a different area.)


*Visualizing with Truth Table*

|---+-----------------+-----------------------+------------------+------------------+---|
|   |       <c>       |          <c>          |       <c>        |       <c>        |   |
|   | \(\phi\) (Raining) | \(\psi\) (Ground is wet) | \(\phi \implies \psi\) | \(\psi \implies \phi\) |   |
|---+-----------------+-----------------------+------------------+------------------+---|
| / |        <        |           <           |        <         |        <         | > |
|   |        T        |           T           |        T         |        T         |   |
|   |        T        |           F           |        F         |        T         |   |
|   |        F        |           T           |        T         |        F         |   |
|   |        F        |           F           |        T         |        T         |   |
|---+-----------------+-----------------------+------------------+------------------+---|


*B*: Consider the statements:

  - \(\phi\): "I go to the Tour de France."
  - \(\psi\): "I have a bike."

*"\(\phi\) only if \(\psi\)" \(\phi \implies \psi\)*

This means: "I go to the Tour de France only if I have a bike."

    - In logical terms: \(\phi \implies \psi\).

      This implies that if you are going to the Tour de France, you must have a bike. Going to the Tour de France is
      conditional upon having a bike. If you don't have a bike, you can't go to the tour de France. However, it does
      *not* imply that having a bike means you are going to the Tour de France. You could have a bike and not go to the
      Tour de France.

*"if \(\psi\), then \(\phi\)" \(\psi \implies \phi\)*

This means: "If I have a bike, then I go to the Tour de France."

    - In logical terms: \(\psi \implies \phi\).

      This implies that having a bike means you must be going to the tour de France. If you have a bike, then you are
      definitely participating in the Tour de France. However, it does *not* imply that going to the Tour de France
      requires having a bike. You could be going to the Tour de France without having a bike, perhaps as spectator or in
      some other capacity.

*Analysis Table of truth*

- *"\(\phi\) only if \(\psi\)" \(\phi \implies \psi\)*

  - If \(\phi\) (I go to the Tour de France) is true, and \(\psi\) (I have a bike) is true, then the statement is true.

  - If \(\phi\) is true, and \(\psi\) is false, then the statement is false because going to the Tour de France should mean
    you have a bike.

  - If \(\phi\) is false (I don't go to the Tour de France), then the statement is true regardless of \(\psi\), because not
    going to the Tour de France does no contradict having a bike.

  - If (\phi\) and \(\psi\) are both false, the statement is true because not going to the Tour de France and not having a
    bike aligns the condition.

- *"if \(\psi\), then \(\phi\)" \(\psi \implies \phi\)*

  - If \(\psi\) (I have a bike) is true, and \(\phi\) (I go to the Tour de France) is true, then the statement is true.

  - If \(\psi\) is true and \(\phi\) is false, the statement is false because having a bike should mean you are going to the
    Tour de France.

  - If \(\psi\) (I don't have a bike) is false, the statement is true regardless of \(\phi\), because not having a bike does
    not require going to the Tour de France.

  - If \(\psi\) and \(\phi\) are both false, the statement is true because not having a bike and not going to the Tour de
    France aligns with the condition.

*** \(\psi\) if \(\phi\)

This is just different way of saying: "If \(\phi\), then \(\psi\)". It mean the same thing as #1.

*Example*
  - \(\psi\): It is raining.
  - \(\phi\): The ground is wet.
  - Statement: If it is raining, the ground is wet.

*** \(\psi\) Whenever \(\phi\)

This is just different way of saying that \(\psi\) happens every time \(\phi\) happens

*Example*
  - \(\psi\): You press the light switch.
  - \(\phi\): The light turns on.
  - Statement: The light turns on whenever you pres the light switch.

*** \(\psi\) is necessary for \(\phi\)

This means that \(\psi\) must be true for \(\phi\) to be true. If \(\phi\) is true, then \(\psi\) has to be true as well.

*Example*
  - \(\psi\): You can graduate.
  - \(\phi\): You have passed all exam
  - Statement: Passing all your exam is necessary for graduating.

*** Summary

It's important to really master this terminology, because it's used all the time, not just in mathematics, but in
science, in analytic reasoning and tough in general.

This is not just mathematical language, this is the language that people use in legal documents, in logical arguments,
in analytic arguments, and in discussion and so forth.

So understanding language as it's used is very important in many walks of life; And having introduced terminology commonly
associated with implication, we have an associated terminology for equivalence.

** Equivalence Terminology "\(\phi \iff \psi\)"

\begin{center}
\text{"\(\phi\) is equivalent to \(\psi\)" is itself \uline{equivalent to}}
\end{center}

By the way this already shows how ubiquitous the equivalence is, because the obvious word to describe this.

The obvious way to describe that ("\(\phi\) is equivalent to \(\psi\)") is equivalent to something is to use world
"equivalence" as well. It mean, equivalence is just very basic concept in mathematics.

So this sentence ("\(\phi\) is equivalent to \(\psi\)") or statement, it's claim is itself equivalent to:

*** \(\phi\) is necessary and sufficient for \(\psi\)

Notice we combining /necessary/ and /sufficient/. With necessary we have \(\psi\) before \(\phi\) ("\(\phi\) is sufficient fit
\(\phi\)"), with sufficient we have \(\phi\) before \(\psi\) ("\(\phi\) is sufficient for \(\psi\)") that gets us the implication in
both directions, and equivalence means /implication in both directions/.

So, the fact that it's in both direction is captured by the fact that we have both sufficient and necessary with below
expression:

*** \(\phi\) if and only if \(\psi\)

Similarly with "if and only if" it combines /only if/ ("\(phi\) only if \(psi\)") where \(\phi\) comes before \(\psi\), with /if/,
("\(\psi\) if \(\phi\)") where \(\psi\) comes before \(\phi\). So both in this cases, we have an implication from '\(\phi\) to \(\psi\)',
and from \(\psi\) to \(\phi\).

Final remark, this expression is often abbreviated */IFF/*. IFF is standard mathematicians abbreviation for 'if and only
if'.

So, 'if and only if' or 'iff' means the two things are equivalent.

Okay, once you've mastered this terminology you should be able to read and make sense of pretty well any mathematics
that you come across. That doesn't mean to say you understand the mathematics itself, but at least you should be able to
understand what it's talking about.

That's a first step towards understanding the mathematics itself. The rest is really up to you to spend some time
mastering the concepts and the associated terminology.

** Quiz Lecture 4

This quiz comes in four parts.

*** Quiz - Part 1 -- 1

Which of the following conditions is necessary for the natural number \(n\) to be a multiple of 10?

1. \(n\) is a multiple of 5.

2. \(n\) is a multiple of 20.

3. \(n\) is even and a multiple of 5.

4. \(n\) = 100.

5. \(n^2\) is multiple of 100.

*A*:

To answer this tricky question, we have to ask ourselves. "Does \(n\) being a multiple of 10 imply the statement?" To be
necessary, \(n\) being a multiple of 10 has to imply the statement.

1. \(n\) is a multiple of 5. [T]

   - A number that is multiple of 10 is also a multiple of 5 because \(10 = 2 X 5\)

   - However, not every multiple of 5 is a multiple of 10 (e.g, 15 is multiple of 5 but not 10).

   - Therefore, this condition is not sufficient, *but* it is part of being a multiple of 10.

2. \(n\) is a multiple of 20, [F]

   - Any number that is multiple of 20 is also multiple of 10 because \(20 = X 10\)

   - This condition is sufficient but not necessary since a multiple of 10 does not have to be a multiple of 20 (e.g, 10
     is a multiple of 10 but not 20).

3. \(n\) is even and a multiple of 5 [T]

   - If \(n\) is even, it divisible by 2.

   - If \(n\) is also multiple by 5, then \(n\) must be a multiple of \(2 X 5 = 10\).

   - Therefore, this condition is both necessary and sufficient for \(n\) to be a multiple of 10.

4. \(n\) = 100 [F]

   - This is specific case of multiple of 10, but it is not necessary for \(n\) to equal 100 to be a multiple of 10
     (e.g, 10, 20, and 30 are also multiple of 10).

   - Therefore, this conditions is not necessary.

5. \(n^2\) is multiple of 100. [T]

   - If \(n^2\) is multiple of 100, then \(n\) must of 10 because if \(n\) were not a multiple of 10, \(n^2\) could not
     be a multiple of 10.

   - Thus, this condition is necessary for \(n\) to be multiple of 10.


After evaluating each condition, the necessary condition for \(n\) to be a multiple of 10 is:

3. \(n\) is even and a multiple of 5.

   This condition ensure that \(n\) is divisible by both 2 and 5, which makes it divisible by 10. Additionally,
   condition 5 (\(n^2\) is multiple of 100) is also valid, but condition 3 is more straightforward and directly confirms
   the requirement.

*** Quiz - Part 1 -- 2

Which of the following conditions is sufficient for the natural number \(n\) to be a multiple of 10?

1. \(n\) is a multiple of 5.

2. \(n\) is a multiple of 20.

3. \(n\) is even and a multiple of 5.

4. \(n\) = 100.

5. \(n^2\) is multiple of 100.

*A:*

1. \(n\) is a multiple of 5. [F]

2. \(n\) is a multiple of 20. [T]

3. \(n\) is even and a multiple of 5. [T]

4. \(n\) = 100 [T]

5. \(n^2\) is multiple of 100. [T]

*** Quiz - Part 1 -- 3

Which of the following conditions is necessary and sufficient for the natural number \(n\) to be a multiple of 10?

1. \(n\) is a multiple of 5.

2. \(n\) is a multiple of 20.

3. \(n\) is even and a multiple of 5.

4. \(n\) = 100.

5. \(n^2\) is multiple of 100.

*A:*

|---+-----+-----------+------------+-----------+---|
|   | <c> |    <c>    |    <c>     |    <c>    |   |
|   |     | Necessity | Sufficient | N \(\land\) S |   |
|---+-----+-----------+------------+-----------+---|
| / |  <  |     <     |     <      |     <     | > |
|   |  1  |     T     |     F      |     F     |   |
|   |  2  |     F     |     T      |     F     |   |
|   |  3  |     T     |     T      |     T     |   |
|   |  4  |     F     |     T      |     F     |   |
|   |  5  |     T     |     T      |     T     |   |
|---+-----+-----------+------------+-----------+---|

So the answer is number 3 and number 5.

*** Quiz - Part 1 -- 4

Identify the antecedent in each of the following conditional:

  1 If the alarm rings, every one leaves

  2 Everyone leaves if the alarm rings

  3 Keith cycles only if the sun shines

  4 Joe leaves whenever Amy arrives

*A:*

The following sentence is the antecedent:

1. "The alarm rings"

2. "The alarm rings"

3. "Keith cycles"

4. "Amy arrives"

** Summary

So far, I've distinguish between genuine implication and equivalents, and they're far more counterparts. The conditional
and bi-conditional[fn:4], in the daily work however, Mathematicians are very not particular. For instance, we often use
the arrow symbol (\(\implies\)) as an abbreviation for implies. On the double headed arrow (\(\iff\)) is an abbreviation
for is equivalent to.

Although this is very confusing for beginners, it's simply the way a mathematical practice is evolved and there's no
getting around it. In fact, once you get used to the notions, it's not all this confusing as it might seem at first and
here is why: The conditional and bi-conditional only differ from implication and equivalents in situation that not
adrise in the cause of normal mathematical practice. In any real mathematical context, the conditional effectively is
implication, and the bi-conditional effectively is equivalent.

So having made note of where the formal notions differ from the everyday ones, mathematicians simply move on and turn
their attention to other things. The very act of formulating definitions creates an understanding of implication and
equivalence that allows us to use the everyday notion safely.

Of course, computer programmer and people who develop aircraft control systems don't have such freedom. They have to
make sure all the notions in their programs are defined and give answers in all circumstances.

Okay, that's the end of the lecture-IV. As I said at the start, it's been a fairly short lecture. My reason for keeping
the lecture is that the upcoming is much longer than the others, it has to be.

Implication and equivalence are the heart of mathematics. Mastery of those concepts and of the terminology associated
with them is fundamental to mathematical thinking.

You simply have to master implication and equivalence before you can go much further; And there's only one way to
achieve mastery, right? Remember the story of the elderly lady who approached a New York City policeman and asked,
officer, how do I get to Carnegie Hall? The officer smiled and said, lady, there's only one way, practice, practice,
practice. So, I suggest you carve out some time, grab some food and drink, and head off somewhere quiet to complete as
much of assignment-IV as you possible can.

* Assignment-4 for Lecture-IV

The assignment is fairly log, but it deals with a number of (related) crucial notions that pervade modern mathematics.
It's impossible to progress in advanced mathematics without mastering these ideas. You probably won't be able to get it
all done before the next lecture, but keep coming back to it until you have at least tried all the questions. The
concepts and methods covered by this assignment are the key to mathematical thinking, and work on this one assignment
will yield wide-ranging benefits not just in mathematics but in many other parts of your life.

** Assignment 4 - Part 1

*Q*: Build a truth table to prove the claim I made earlier that "\(\phi \iff \psi\)" is true if \(\phi\) and \(\psi\) are both true,
or both false, and "\(\phi \iff \psi\)" is false if exactly one of \(\phi\), \(\psi\) is true and the other false. (To constitute a
proof, your table should have columns that shows how the entries for "\(\phi \iff \psi\)" are derived, one operate at a time.)

*A*: To Prove the claim "\(\phi \iff \psi\)" is true if \(\phi\) and \(\psi\) are both true or both false, and "\(\phi \iff \psi\)" is false
if exactly one of \(\phi\), \(\psi\) is true and the other is false, we will build a truth table.

In this truth table, we will sow the steps to derive \(\phi \implies \psi\) using a basic logical operations.

*Steps to Derive \(\phi \iff \psi\)*

  1. List the possible truth values for \(\phi\) and \(\psi\).

  2. Compute \(\phi \implies \psi\).

  3. Compute \(\psi \implies \phi\).

  4. Compute \((\phi \implies \psi) \land (\psi \implies \phi)\), which is equivalent to \(\phi \iff \psi\).

Here is the truth table:

|---+-------+-------+------------------+------------------+--------------------------------------------------------+---|
|   |  <c>  |  <c>  |       <c>        |       <c>        |                          <c>                           |   |
|   | \(\phi\) | \(\psi\) | \(\phi \implies \psi\) | \(\psi \implies \phi\) | \((\phi \implies \psi) \land (\psi \implies \phi)\) (i.e \(\phi \iff \psi\)) |   |
|---+-------+-------+------------------+------------------+--------------------------------------------------------+---|
| / |   <   |   <   |        <         |        <         |                           <                            | > |
|   |   T   |   T   |        T         |        T         |                           T                            |   |
|   |   T   |   F   |        F         |        T         |                           F                            |   |
|   |   F   |   T   |        T         |        F         |                           F                            |   |
|   |   F   |   F   |        T         |        T         |                           T                            |   |
|---+-------+-------+------------------+------------------+--------------------------------------------------------+---|

*Explanation*:

  - \(\phi \implies \psi\):

    - This is true when either \(\phi\) is false or \(\psi\) is true (if \(\phi\) is true, \(\psi\) must be true).

    - \(\phi \implies \psi\) is false only when \(\phi\) is true and \(\psi\) is false.

  - \(\psi \implies \phi\):

    - This is true when either \(\psi\) is false or \(\phi\) is true (if \(\psi\) is true, \(\phi\) must be true).

    -
      \(\psi \implies \phi\) is false only when \(\psi\) is true and \(\phi\) is false.

  - \((\phi \implies \psi) \land (\psi \implies \phi)\):

    - This is true only when both \(\phi \implies \psi\) and \(\psi \implies \phi\) are true.

    - This happens when \(\phi\) and \(\psi\) are both true or both false.

 *Conclusion*:

 The truth table confirm the claim:

    - \(\phi \iff \psi\) is true when \(\phi\) and \(\psi\) are both true or both false.

    - \(\phi \iff \psi\) is false when exactly one of \(\phi\) and \(\psi\) is true and the other is false.

** Assignment 4 - Part 2

*Q:* Build a truth table to show that

\begin{center}
\text{\((\phi \iff \psi) \iff (\neg\phi \lor \psi)\)}
\end{center}

Is true for all truth values of \(\phi\) and \(\psi\). A statement whose truth values are all T is called /logical validity/,
or sometimes /tautology/.


*A:* To prove that \((\phi \iff \psi) \iff (\neg\phi \lor \psi)\) is a tautology, we need to construct a truth table that shows this expression is true for all possible truth values of \(\phi\) and \(\psi\).

*Steps to Derive \((\phi \iff \psi) \iff (\neg\phi \lor \psi)\)*:

    1. List the possible truth values for \(\phi\) and \(\psi\)

    2. Compute \(\phi \iff \psi\)

    3. Compute \(\neg\phi\)

    4. Compute \(\neg\phi \lor \psi\)

    5. Compute \((\phi \iff \psi) \iff (\neg\phi \lor \psi)\).

Here is the truth table:

|---+-------+-------+--------------+--------+------------+------------------------------+---|
|   |  <c>  |  <c>  |     <c>      |  <c>   |    <c>     |             <c>              |   |
|   | \(\phi\) | \(\psi\) | \(\phi \iff \psi\) | \(\neg\phi\) | \(\neg\phi \lor \psi\) | \((\phi \iff \psi) \iff (\neg\phi \lor \psi)\) |   |
|---+-------+-------+--------------+--------+------------+------------------------------+---|
| / |   <   |   <   |      <       |   <    |     <      |              <               | > |
|   |   T   |   T   |      T       |   F    |     T      |              T               |   |
|   |   T   |   F   |      F       |   F    |     F      |              T               |   |
|   |   F   |   T   |      F       |   T    |     T      |              F               |   |
|   |   F   |   F   |      T       |   T    |     T      |              F               |   |
|---+-------+-------+--------------+--------+------------+------------------------------+---|

*Explanation*:

- \(\phi \iff \psi\):

  - True when \(\phi\) and \(\psi\) are both true or both false.

  - False when \(\phi\) and \(\psi\) have different truth values.

- \(\neg\phi\)

  - Negation of \(\phi\), true when \(\phi\) is false, false when \(\phi\) is true.

- \(\neg\phi \lor \psi\)

  - True when at least one \(\neg\phi\) or \(\psi\) is true.

- \((\phi \iff \psi) \iff (\neg\phi \lor \psi)\)

  - True if both expression have the same truth value (both true or both false)

*Conclusion*:

- The truth table conform that \((\phi \iff \psi) \iff (\neg\phi \lor \psi)\) is not true for all possible truth values of \(\phi\) and
  \(\psi\). Hence \((\phi \iff \psi) \iff (\neg\phi \lor \psi)\) is not tautology, as it is not true for every combination of truth values
  for \(\phi\) and \(\psi\).

** Assignment 4 - Part 3

*Q:* Build a truth table to show that

\begin{center}
\text{\((\phi \centernot\implies \psi) \iff (\phi \land \neg\psi)\) }
\end{center}

Is a /tautology/.

*A*: To show that \((\phi \centernot\implies \psi) \iff \(\phi \land \neg\psi)\) is tautoglogy, we need to build a truth table and verify
if this expression holds true for all possible truth values of \(\phi\) and \(\psi\).

Let's break down the component of the expression:

*Understand the components*:

  1. \(\phi \centernot\implies \psi\): This represent the negation of \(\phi \implies \psi\). Recall that \(\phi \implies \psi\) is false
     only when \(\phi\) is true and \(\psi\) is false. Thus, \(\phi \centernot\implies \psi\) is true when \(\phi\) is true and \(\psi\)
     is false.

  2. \(\phi \land \neg\psi\): This represent the conjunction of \(\phi\) and the negation of \(\psi\). This is true only when \(\phi\) is true
     and \(\psi\) is false.

We aim to prove that \(\phi \centernot\implies \psi\) is equivalent to \(\phi \land \neg\psi\), meaning both should have the same truth
value for all combinations of \(\phi\) and \(\psi\).

Here is the truth table:

|---+-------+-------+--------+------------------+----------------------------+------------+----------------------------------------------+---|
|   |  <c>  |  <c>  |  <c>   |       <c>        |            <c>             |    <c>     |                     <c>                      |   |
|   | \(\phi\) | \(\psi\) | \(\neg\psi\) | \(\phi \implies \psi\) | \(\phi \centernot\implies \psi\) | \(\phi \land \neg\psi\) | \((phi \centernot\implies \psi) \iff (\phi \land \neg\psi)\) |   |
|---+-------+-------+--------+------------------+----------------------------+------------+----------------------------------------------+---|
| / |   <   |   <   |   <    |        <         |             <              |     <      |                      <                       | > |
|   |   T   |   T   |   F    |        T         |             F              |     F      |                      T                       |   |
|   |   T   |   F   |   T    |        F         |             T              |     T      |                      T                       |   |
|   |   F   |   T   |   F    |        T         |             F              |     F      |                      T                       |   |
|   |   F   |   F   |   T    |        T         |             F              |     F      |                      T                       |   |
|---+-------+-------+--------+------------------+----------------------------+------------+----------------------------------------------+---|

*Explanation*:

  1. \(\phi \implies \psi\)

     - True when \(\phi\) is false or \(\psi\) is true.

     - False only when \(\phi\) is true and \(\psi\) is false.

  2. \(\phi \centernot\implies \psi\)

     - negation of \(\phi \implies \psi\)

     - True when \(\phi\) is true and \(\psi\) is false.

  3. \(\neg\psi\)

     - Negation of \(\psi\).

     - True when \(\psi\) is false.

     - False when \(\psi\) is true.

  4. \(\phi \land \neg\psi\)

     - Conjunction of \(\phi\) and \(\neg\psi\).

     - True when \(\phi\) is true and \(\psi\) is false.

     - False otherwise.

  5. \((\phi centernot\implies \psi) \iff (\phi \land \neg\psi)\)

     - This bi-conditional checks if \(\phi \centernot\implies \psi\) and \(\phi \land \psi\) have the same truth value.

*Conclusion*:

The truth table confirms that \((\phi \centernot\implies \psi) \iff (\phi \land \neg\psi)\) is true for all possible truth values of \(\phi\)
and \(\psi\). Hence \((\phi \centernot\implies \psi) \iff (\phi \land \neg\psi)\) is tautology, as it is true for every combination of truth
values for \(\phi\) and \(\psi\).

** Assignment 4 - Part 4

*Q* The ancient Greek formulated a basic rule of reasoning for proving mathematical statements. Called /modus ponens/, it says
that if you know \(\phi\) and you know \(\phi \implies \psi\), then you can conclude \(\psi\),

(a) Construct a truth table for the logical statement

\begin{center}
\text{\([\phi \land (\phi \implies \psi)] \implies \psi\)}
\end{center}

(b) Explain how the truth table you obtain demonstrates that /modus ponens/ is a valid rule of inference[fn:5].

*A*: Let's start by constructing the truth table for the logical \([\phi \land (\phi \implies \psi)] \implies \psi\). Then we'll
use the truth table to demonstrate that modus ponens is a valid of inference.

*Step-by-Step Truth Table Construction*:

  1. List all possible truth values for \(\phi\) and \(\psi\).

  2. Compute \(\phi \implies \psi\).

  3. Compute \(\phi \land (\phi \implies \psi)\).

  4. Compute \([\phi \land (\phi \implies \psi) \implies \psi]\).

Truth Table:

|---+-------+-------+------------------+------------------------+-------------------------------------+---|
|   |  <c>  |  <c>  |       <c>        |          <c>           |                 <c>                 |   |
|   | \(\phi\) | \(\psi\) | \(\phi \implies \psi\) | \(\phi \land (\phi \implies \psi)\) | \([\phi \land (\phi \implies \psi) \implies \psi]\) |   |
|---+-------+-------+------------------+------------------------+-------------------------------------+---|
| / |   <   |   <   |        <         |           <            |                  <                  | > |
|   |   T   |   T   |        T         |           T            |                  T                  |   |
|   |   T   |   F   |        F         |           F            |                  T                  |   |
|   |   F   |   T   |        T         |           F            |                  T                  |   |
|   |   F   |   F   |        T         |           F            |                  T                  |   |
|---+-------+-------+------------------+------------------------+-------------------------------------+---|

*Explanation of the Truth Table*:

1. First row \((\phi = T, \psi = T)\)

   - \(\phi \implies \psi\) = T (since T implies T is T)
   - \(\phi \land (\phi \implies \psi)\) = T (since T and T is T)
   - \([\phi \land (\phi \implies \psi)] \implies \psi\) = T (since T implies T is T)

2. Second row \((\phi = T, \psi = F)\)

   - \(\phi \implies \psi\) = F (since T implies F is F)
   - \(\phi \land (\phi \implies \psi)\) = F (since T and F is F)
   - \([\phi \land (\phi \implies \psi)] \implies \psi\) = T (since F implies F is T)

3. Third row \((\phi = F, \psi = T)\)

   - \(\phi \implies \psi\) = T (since F implies T is T)
   - \(\phi \land (\phi \implies \psi)\) = F (since F and T is T)
   - \([\phi \land (\phi \implies \psi)] \implies \psi\) = T (since F implies T is T)

4. Fourth row \((\phi = F, \psi = F)\)

   - \(\phi \implies \psi\) = T (since F implies F is T)
   - \(\phi \land (\phi \implies \psi)\) = F (since F and T is F)
   - \([\phi \land (\phi \implies \psi)] \implies \psi\) = T (since F implies F is T)


*Explanation of Modus Ponens*:

The truth table correctly shows that the statement \([\phi \land (\phi \implies \psi)] \implies \psi\) is always true:

  - *First Row*: \(\phi\) is true, \(\psi\) is true, hence \(\phi \land (\phi \implies \psi\) is true. Thus, \([\phi \land (\phi \implies \psi)]
    \implies \psi\) is true.

  - *Second Row*: \(\phi\) is true, \(\psi\) is false, hence \(\phi \land (\phi \implies \psi\) is false. Thus, \([\phi \land (\phi \implies \psi)]
    \implies \psi\) is true (since false implies anything is true).

  - *First Row*: \(\phi\) is false, \(\psi\) is true, \(\phi \implies \psi\) is true (vacuously). Hence \(\phi \land (\phi \implies \psi\) is
    false. Thus, \([\phi \land (\phi \implies \psi)] \implies \psi\) is true.

  - *First Row*: \(\phi\) is false, \(\psi\) is false, \(\phi \implies \psi\) is true (vacuously). hence \(\phi \land (\phi \implies \psi\) is
    false. Thus, \([\phi \land (\phi \implies \psi)] \implies \psi\) is true.

This demonstrates that modus ponens is a valid rule of inference:

  - When \(\phi\) is true and \(\phi \implies \psi\) is true, \(\psi\) must be true.

  - In all other cases, the antecedent \(\phi \land (\phi \implies \psi)\) is false, making the implication true because an
    implication with a false antecedent is always true.

Thus, \([\phi \land (\phi \implies \psi) \implies \psi)]\) is a /tautology/, confirming the validity of modus ponens.

*Additional*: What means 'vacuously' in above sentence?

In logic and mathematics, a statement is said to be *vacuously true* if the asserts that something holds for all
elements of an empty set or if it asserts that a conditional statement is true when the antecedent (the "if" part) is
false.

In the context of implication, \(\phi \implies \psi\), when \(\phi\) (the antecedent) is false, the implication is considered
true regardless of truth value of \(\psi\) (the consequent). This is because the implication doesn't have to prove
anything; it's not making any demands or requirements when the starting point (the antecedent) isn't met.

Detailed Example:

Let's consider the specific row in the truth table:

  - \(\phi\) *is false* (for example, \(\phi\): "I go to the beach")

  - \(\psi\) *is true* (for example: \(\psi\) : "It is sunny")

The implication \(\phi \implies \psi\) ("If I go to the beach, then its sunny") is vacuously true because I did not go to the
beach, so the condition does not apply. Whether it is sunny or not is irrelevant to the truth of the implication.

Conclusion:

The term "vacuously true" highlights that the truth of the implication in these cases doesn't provide meaningful
information about the relationship between \(\phi\) and \(\psi\); it is true simply because the antecedent is /false/, and no
further condition needs to be checked.

** Assignment 4 - Part 5

*Q:* [This question has a long set-up. The question itself is the very last sentence. *TAKE YOUR TIME*.]

One way to prove

\begin{center}
\text{\(\neg(\phi \land \psi)\) and \((\neg\phi) \lor (\neg\psi)\)}
\end{center}

Are equivalent is to show they have the same truth table:

|---+-------+-------+-----------+--------------+--------+--------+-----------------+---|
|   |  <c>  |  <c>  |    <c>    |     <c>      |  <c>   |  <c>   |       <c>       |   |
|   |       |       |           |      *       |        |        |        *        |   |
|   | \(\phi\) | \(\psi\) | \(\phi \land \psi\) | \(\neg(\phi \land \psi)\) | \(\neg\phi\) | \(\neg\psi\) | \((\neg\phi) \lor (\neg\psi)\) |   |
|---+-------+-------+-----------+--------------+--------+--------+-----------------+---|
| / |   <   |   <   |     <     |      <       |   <    |   <    |        <        | > |
|   |       |       |           |              |        |        |                 |   |
|   |   T   |   T   |     T     |      F       |   F    |   F    |        F        |   |
|   |   T   |   F   |     F     |      T       |   F    |   T    |        T        |   |
|   |   F   |   T   |     F     |      T       |   T    |   F    |        T        |   |
|   |   F   |   F   |     F     |      T       |   T    |   T    |        T        |   |
|---+-------+-------+-----------+--------------+--------+--------+-----------------+---|

Since the two column marked * are identical, we know that the two expressions are equivalent.

Thus negation has the affect it changes \(\lor\) into \(\land\) and changes \(\land\) into \(\lor\). An alternative approach way to
prove this is to argue directly with the meaning of the first statement:

  1. \(\phi \land \psi\) means both \(\phi\) and \(\psi\) are true.

  2. Thus \(\neg(\phi \land \psi)\) means is not the case that both \(\psi\) and \(\psi\) are true.

  3. If they are not both true, then at least one of \(\psi\), \(\psi\) must be false.

  4. This is clearly the same as saying that at least one of \(\neg\phi\) and \(\neg\psi\) is true. (By the definition of negation).

  5. By the meaning of /or/, this can be expressed as \((\neg\phi) \lor (\neg\psi)\).

Provide an analogues logical arguments to show that \(\neg(\phi \lor \psi)\) and \((\neg\phi) \lor (\neg\psi)\) are equivalent.

*A*: To prove that \(\neg(\phi \lor \psi)\) and \((\neg\phi) \land (\neg\psi)\) are equivalent, we can use logical reasoning similar to the argument
provided for \(\neg(\phi \lor \psi)\) and \((\neg\phi) \land (\neg\psi)\). Here is the step-by-step argument:

1. Definition of \(\phi \lor \psi\):

   \(\phi \lor \psi\) means that at least one of \(\phi\) or \(\psi\) is true.

2. Negation of \(\phi \lor \psi\):

   \(\neg(\phi \lor \phi)\) means it is not case that at least one of \(\phi\) or \(\psi\) is true. In other words, neither \(\phi\) nor
   \(\psi\) is true.

3. Rephrasing the negation:

   If neither \(\phi\) or \(\psi\) is true, then both \(\phi\) and \(\psi\) must be false.

4. Using the definition of negation:

   Saying that both \(\phi\) and \(\psi\) are false is the same as saying that \(\neg\phi\) and \(\neg\psi\) are both true.

5. Expressing with logical "and":

   By the meaning of "and", this can be expressed as \(\neg\phi) \land (\neg\psi)\)\).

Thus, we have shown that through logical reason that:

\begin{center}
\text{\(\neg(\phi \land \psi) \equiv (\neg\phi) \lor (\neg\psi)\)}
\end{center}

*Truth Table Verification*:

- In the first row, \(\phi\) and \(\psi\) are both true, so \(\phi \lor \psi\) is true, and \(\neg(\phi \lor \psi)\) is false. \(\neg\phi\) and \(\neg\psi\)
  are both false, so \((\neg\phi) \land (\neg\psi)\) is false.

- In the second row, \(\phi\) is true and \(\psi\) is false, so \(\phi \lor \psi\) is true, and \(\neg(\phi \lor \psi)\) is false. \(\neg\phi\) is false
  and \(\neg\psi\) is true, so \((\neg\phi) \land (\neg\psi)\) is false.

- In the third row, \(\phi\) is false and \(\psi\) is true, so \(\phi \lor \psi\) is true, and \(\neg(\phi \lor \psi)\) is false. \(\neg\phi\) is true
  and \(\neg\psi\) is false, so \((\neg\phi) \land (\neg\psi)\) is false.

- In the fourth row, \(\phi\) and \(\psi\) are both false, so \(\phi \lor \psi\) is false, and \(\neg(\phi \lor \psi)\) is true. \(\neg\phi\) and \(\neg\psi\)
  are both true, so \((\neg\phi) \land (\neg\psi)\) is true.

This demonstrates that the two expression are logically equivalent, making the argument and the truth table consistent
with each other.

** Assignment 4 - Part 6

*Q* By a /denial/ of a statement \(\phi\) we mean any statement equivalent to \(\neg\phi\). Give a useful (and hence natural
 sounding) denial of each the following statement with math symbol represent:

   1. 34.159 is prime number

   2. Roses are red and violets are blue

   3. If there are no hamburgers, I'll have a hot dog.

   4. Fred will go but he will not play.

   5. The number \(x\) is either negative or greater than 10.

   6. We will win the first game or the second.

*A*: Let's create denial for each of the statement. These denials will be logically equivalent to the negation of the
original statement and will be presented in a natural-sounding manner.

   1. 34.159 is a prime number

      *Original statement*: "34.159 is a prime number".

        - *Mathematical Representation*: Let \(P\) represent "34.159 is a prime number".

        - *Antecedent*: "34.159".

        - *Consequence*: "is a prime number".

      *Denial*: "34.159 is not a prime number".

        - *Mathematical Representation*: \(\neg P\)

   2. Roses are red and violets are blue

      *Original statement*: "Roses are red and violets are blue"

        - *Mathematical Representation*: Let \(R\) is represent "Roses are red" and \(V\) represent "Violet are blue",

        - *Antecedent*: "Roses are red".

        - *Consequence*: "Violets are blue".

      *Denial*: "Roses are not red and violets are not blue"

        - *Mathematical Representation*: \(\neg(R \land V) \equiv \neg R \lor \neg V\) it means: is  (\neg(R \land V)\) is equivalent to  \(\neg R \lor \neg V\)

   3. If there are no hamburgers, I'll have a hot dog.

      *Original statement*: "If there are no hamburgers, I'll have a hot dog".

        - *Mathematical Representation*: Let \(H\) represent "There are no hamburgers"a and \(D\) represent "I'll have not a hot dog".

        - *Antecedent*: "If there are no hamburgers".

        - *Consequence*: "I'll have no hot dog".

      *Denial*: "there are no hamburger and I won't have a hot dog" or "there are no hamburger but I won't have a hot dog"

      *Mathematical Representation*: \(\neg(H \implies D)\), which is equivalent to \(H \land \neg D\)

      NOTE: when you got a \(\neg[\phi \implies \psi] : \phi \land \neg\psi\)

   4. Fred will go but he will not play.

      *Original statement*: "Fred will go but he will not play".

        - *Mathematical Representation*: Let \(G\) represent "Fred will go", and \(P\) represent "Fred will play".

        - *Antecedent*: "Fred will go".

        - *Consequence*: "but he will not play".

      *Denial*: "Fred will not go or he will play" or "Fred will play or he won't go".

        - *Mathematical Representation*: \(\neg(G \land \neg P) \equiv \neg G \lor P\) or \(P \lor \neg G\)

   5. The number \(x\) is either negative or greater than 10.

      *Original statement*:"The number \(x\) is either negative or greater than 10."

        - *Mathematical Representation*: Let \(N\) represent "The number \(x\) is negative", and \(G\) represent "The
          number \(x\) is greater than 10".

        - *Antecedent*: "The number \(x\) is either negative".

        - *Consequence*: "or greater than 10".

      *Denial*: "The number \(x\) is neither negative nor greater than 10." or "The number \(x\) is non_negative and
      less than or equal to 10".

        - *Mathematical Representation*: \(\neg(N \lor G) \equiv (\neg N) \land (\neg G)\)

          OR

          -. \(\neg [(x < 0) \lor (x > 10)]\) then,

          -. \((x \ge 0) \land (x \le 10)\) then,

          -. \(0 \le x \le 10\)

        NOTE: Symbols provide a much more efficient way of expressing, and indeed, for dealing with the negation.

   6. We will win the first game or the second.

      *Original statement*: "We will win the first game of or the second".

        - *Mathematical Representation*: Let \(W_1\) represent "We will win the first game" and \(W_2\) represent "We
          will win the second game".

        - *Antecedent*: "We will win the first game".

        - *Consequence*: "or the second".

      *Denial*: "We will not win the first game and we will not win the second". Or "We will lose the first two game".

        - *Mathematical Representation*: \(\neg(W_1 \lor W_2)\) \equiv \((\neg W_1) \land (\neg W_2)\)

*Conclusion*:

   These denials provide alternative statement that are logically equivalent tho the negation of the original statements
   while sounding natural and clear.

   Dealing with language precisesly is actually not easy because our mind jump ahead.

   Human beings are very smart wit using language in everyday terms. But the cost is that we drop precision, we think in terms of
   the way we understanding the meanings rather than what the literal meaning are.

   The whole point of this analysis of language that we're doing now, is to be very-very precise.

** Assignment 4 - Part 7

*Q* Show that \(\phi \iff \psi\) is equivalent to \((\neg\phi) \iff (\neg\psi)\).

*A* Tho show that \(\phi \iff \psi\) is equivalent to \((\neg\phi) \iff (\neg\psi)\), we can use logical equivalences and truth tables.

*Logical Equivalences*:

  1. Definition of Biconditional: \(\phi \iff \psi\) means \((\phi implies \psi) \land (\psi \implies \phi)\).

  2. Negation of Implication: \(\neg(\phi \implies \psi)\) is equivalent to \(\phi \land \psi\)

*Proof using Logical Equivalences*:

  1. Start with \(\phi \iff \psi\):

     \(\phi \implies \psi \equiv (\phi \implies \psi) \land (\psi implies \phi)\)

  2. Translate each implication into an equivalent form:

     \(\phi \implies \psi \equiv \neg\phi \lor \psi \psi \implies \psi \equiv \neg\psi \lor \phi\)

  3. Substitute these into the biconditional:

     \((\phi \implies \psi) \land (\psi \implies \phi) \equiv (\neg\phi \lor \psi) \land (\neg\psi \lor \phi)\)

  4. Now consider \((\neg\phi) \implies (\neg\psi)\):

     \((\neg\phi) \iff (\neg\psi) \equiv ((\neg\phi \implies \neg\psi) \land (\neg\psi \implies \neg\phi))\)

  5. Translate each implication similarly:

     \(\neg\phi \implies \neg\psi \equiv \neg\psi \neg\psi implies \neg\phi \equiv \psi \lor \neg\phi\)

  6. Substitute these back:

     \(((\neg\phi \implies \neg\psi) \lor (\neg\psi \implies \neg\phi)) \equiv (\phi \lor \neg\psi) \land (\psi \lor \neg\phi)\)

*Truth Table*:

To confirm the equivalence, we can construct a truth table for both \(\phi \iff \psi\) and \((\neg\phi) \iff (\neg\psi)\):

|---+-------+-------+-------+-------+--------------+--------------------+---|
|   |  <c>  |  <c>  |  <c>  |  <c>  |     <c>      |        <c>         |   |
|   | \(\phi\) | \(\psi\) | \(\neg\phi) | \(\neg\psi) | \(\phi \iff \psi\) | \((\neg\phi) \iff (\neg\psi)\) |   |
|---+-------+-------+-------+-------+--------------+--------------------+---|
| / |   <   |   <   |   <   |   <   |      <       |         <          | > |
|   |   T   |   T   |   F   |   F   |      T       |         T          |   |
|   |   T   |   F   |   F   |   T   |      F       |         F          |   |
|   |   F   |   T   |   T   |   F   |      F       |         F          |   |
|   |   F   |   F   |   T   |   T   |      T       |         T          |   |
|---+-------+-------+-------+-------+--------------+--------------------+---|

** Assignment 4 - Part 8

*Q* Construct truth tables to illustrate the following:

  1. \(\phi \iff \psi\)
  2. \(\phi \implies (\psi \land 0)\)

*A*: To construct the truth tables for the logical statement \(\phi \iff \psi\) and \(\phi \implies (\psi \land 0)\), we will analyze each row of possible
truth values for \(\phi\) and \(\psi\) and compute the corresponding truth values for the statements:

1. Truth table for \(\phi \iff \psi\)

   |---+-------+-------+--------------+---|
   |   |  <c>  |  <c>  |     <c>      |   |
   |   | \(\phi\) | \(\psi\) | \(\phi \iff \psi\) |   |
   |---+-------+-------+--------------+---|
   | / |   <   |   <   |      <       | > |
   |   |   T   |   T   |      T       |   |
   |   |   T   |   F   |      F       |   |
   |   |   F   |   T   |      F       |   |
   |   |   F   |   F   |      T       |   |
   |---+-------+-------+--------------+---|


2. Truth table for \(\phi \implies (\psi \land 0)\)

   |---+-------+-------+-----------+------------------------+---|
   |   |  <c>  |  <c>  |    <c>    |          <c>           |   |
   |   | \(\phi\) | \(\psi\) | \(\psi \land 0\) | \(\phi \implies (\psi \land 0)\) |   |
   |---+-------+-------+-----------+------------------------+---|
   | / |   <   |   <   |     <     |           <            | > |
   |   |   T   |   T   |  F        |           F            |   |
   |   |   T   |   F   |  F        |           F            |   |
   |   |   F   |   T   |  F        |           T            |   |
   |   |   F   |   F   |  F        |           T            |   |
   |---+-------+-------+-----------+------------------------+---|

3. Comparison of Truth Tables

   Let's compare the truth values between \(\phi \iff \psi\) and \(\phi \implies (\psi \land 0)\) for each combination of \(\phi\) and \(\psi\):

   |---+-------+-------+-----------+------------------------+---|
   |   |  <c>  |  <c>  |    <c>    |          <c>           |   |
   |   | \(\phi\) | \(\psi\) | \(\psi \land 0\) | \(\phi \implies (\psi \land 0)\) |   |
   |---+-------+-------+-----------+------------------------+---|
   | / |   <   |   <   |     <     |           <            | > |
   |   |   T   |   T   |     F     |           F            |   |
   |   |   T   |   F   |     F     |           F            |   |
   |   |   F   |   T   |     F     |           T            |   |
   |   |   F   |   F   |     F     |           T            |   |
   |---+-------+-------+-----------+------------------------+---|

Explanation:

1. For \(\phi \implies \psi\):

   - The statement is true when both \(\phi\) and \(\psi\) are either both true or both false.

   - It is false when one is true and other is false.

2. For \(\phi \implies (\psi \land 0)\):

   - Since \(\psi \land 0\) is always false, the implication \(\phi \implies False\) (which is \(\neg\phi\)) holds.

   - The implication is false only when is true (since true does not imply false.)

Conclusion:

The truth table for \(\phi \iff \psi\) and \(\phi \implies (\psi \land 0)\) are not congruent. This is evidence because the truth values
for the two expression differ for some combination of \(\phi\) and \(\psi\), Specifically:

  - When \(\phi\) is True and \(\psi\) is True, \(\phi \iff \psi\) is True, but \(\phi \implies (\psi \land 0)\) is False.

  - When \(\phi\) is False and \(\psi\) is True, \(\phi \iff \psi\) is False, but \(\phi \implies (\psi \land 0)\) is False.

** Assignment 4 - Part 9

Use truth tables to prove that the following are equivalent:

\begin{center}
\text{\(\phi \implies (\psi \land 0)\) and \((\phi \implies \psi) \land (\phi \implies 0)\)}
\end{center}

*A*: To prove that \(\phi \implies (\psi \land 0)\) and \((\phi \implies \psi) \land (\phi \implies 0)\), we will construct their truth
tables and compare the results.

*Truth table for \(\phi \implies (\psi \land 0)\)*:

   |---+-------+-------+-----------+------------------------+---|
   |   |  <c>  |  <c>  |    <c>    |          <c>           |   |
   |   | \(\phi\) | \(\psi\) | \(\psi \land 0\) | \(\phi \implies (\psi \land 0)\) |   |
   |---+-------+-------+-----------+------------------------+---|
   | / |   <   |   <   |     <     |           <            | > |
   |   |   T   |   T   |     F     |           F            |   |
   |   |   T   |   F   |     F     |           F            |   |
   |   |   F   |   T   |     F     |           T            |   |
   |   |   F   |   F   |     F     |           T            |   |
   |---+-------+-------+-----------+------------------------+---|

*Truth Table for \((\phi \implies \psi) \land (\phi \implies 0)\)*:

Here, \(\phi \implies 0\) simplified to \(\neg\phi\), since \(\phi\) implies false only when \(\phi\) is false.

   |---+-------+-------+------------------+-------------------+-------------------------------------+---|
   |   |  <c>  |  <c>  |       <c>        |        <c>        |                 <c>                 |   |
   |   | \(\phi\) | \(\psi\) | \(\phi \implies \psi\) | \(\phi \implies  0\) | \((\phi \implies \psi) \land (\phi \implies 0)\) |   |
   |---+-------+-------+------------------+-------------------+-------------------------------------+---|
   | / |   <   |   <   |        <         |         <         |                  <                  | > |
   |   |   T   |   T   |        T         |         F         |                  F                  |   |
   |   |   T   |   F   |        F         |         F         |                  F                  |   |
   |   |   F   |   T   |        T         |         F         |                  T                  |   |
   |   |   F   |   F   |        T         |         F         |                  T                  |   |
   |---+-------+-------+------------------+-------------------+-------------------------------------+---|

*Comparison of the Truth Tables*:

Let's compare the truth values of \(\phi \implies (\psi \land 0)\) and \((\phi \implies \psi) land (\phi \implies 0)\) for each
combination of \(\phi\) and \(\psi\):

   |---+-------+-------+------------------------+-------------------------------+---|
   |   |  <c>  |  <c>  |          <c>           |              <c>              |   |
   |   | \(\phi\) | \(\psi\) | \(\phi \implies (\psi \land 0)\) | \((\phi \implies \psi) \land (\psi \land 0)\) |   |
   |---+-------+-------+------------------------+-------------------------------+---|
   | / |   <   |   <   |           <            |               <               | > |
   |   |   T   |   T   |           F            |               F               |   |
   |   |   T   |   F   |           F            |               F               |   |
   |   |   F   |   T   |           T            |               T               |   |
   |   |   F   |   F   |           T            |               T               |   |
   |---+-------+-------+------------------------+-------------------------------+---|

*Conclusion*

The truth tables for \(\phi \implies (\psi \land 0)\) and \((\phi \implies \psi) \land (\phi \implies 0)\) are identical. For each combination
of \(\phi\) and \(\psi\), the truth values of the two expression match exactly.

** Assignment 4 - Part 9A

Use truth tables to prove that the following are equivalent:

1. \(\neg(\phi \implies \psi)\) and \(\phi \land (\neg\psi)\)

2. \(\phi \implies (\psi \lor 0)\) and \((\phi \implies \psi) \land (\phi \implies 0)\)

3. \((\phi \lor \psi) \implies 0\) and \(\phi \implies 0) \land (\psi \implies 0)\)

*A*: Let's construct truth tables to prove the equivalences for each pair of statements:

1. \(\neg(\phi \implies \psi)\) and \(\phi \land \(\neg\psi)\)

   First, let's recall the truth table for \(\phi \implies \psi\):

   |---+-------+-------+------------------+---|
   |   |  <c>  |  <c>  |       <c>        |   |
   |   | \(\phi\) | \(\psi\) | \(\phi \implies \psi\) |   |
   |---+-------+-------+------------------+---|
   | / |   <   |   <   |        <         | > |
   |   |   T   |   T   |        T         |   |
   |   |   T   |   F   |        F         |   |
   |   |   F   |   T   |        T         |   |
   |   |   F   |   F   |        T         |   |
   |---+-------+-------+------------------+---|

   Now, we will construct the truth tables for \(\neg(\phi \implies \psi)\) and \(\phi \land \neg\psi\)

   |---+-------+-------+--------+------------------+---------------------+------------+---|
   |   |  <c>  |  <c>  |  <c>   |       <c>        |         <c>         |    <c>     |   |
   |   | \(\phi\) | \(\psi\) | \(\neg\psi\) | \(\phi \implies \psi\) | \(\neg(\phi \implies \psi)\) | \(\phi \land \neg\psi\) |   |
   |---+-------+-------+--------+------------------+---------------------+------------+---|
   | / |   <   |   <   |   <    |        <         |          <          |     <      | > |
   |   | T     | T     |   F    |  T               | F                   |F           |   |
   |   | T     | F     |   T    |  F               | T                   |T           |   |
   |   | F     | T     |   F    |  T               | F                   |F           |   |
   |   | F     | F     |   T    |  T               | F                   |T           |   |
   |---+-------+-------+--------+------------------+---------------------+------------+---|

   Conclusion:

   The truth tables shows that \(\neg(\phi \implies \psi)\) is true only when \(\phi \implies \psi\) is false, which is when the
   implication itself is false.

   The columns for \(\neg(\phi \implies \psi)\) and \(\phi \land \neg\psi\) are identical, which proves that \(\neg(\phi \implies \psi\) is equivalent
   to \(\phi \land \neg\psi\).

2. \(\phi \implies (\psi \lor 0)\) and \((\phi \implies \psi) \land (\phi \implies 0)\)

   Recall that \(\psi \lor 0\) simplifies to \(\psi\) because \(0\) represent false. So, \(\phi \implies (\psi \lor 0)\) simplifies to \(\phi
   \implies \psi\).

   Now let's construct the truth tables for \(\phi \implies \psi\) and \((\phi \implies \psi) \land (\phi \implies 0)\):

   |---+-------+-------+-----------+------------------+------------------+-------------------------------------+---|
   |   |  <c>  |  <c>  |    <c>    |       <c>        |       <c>        |                 <c>                 |   |
   |   | \(\phi\) | \(\psi\) | \(\phi \lor 0\) | \(\phi \implies \psi\) | \(\phi \implies 0\) | \((\phi \implies \psi) \land (\phi \implies 0)\) |   |
   |---+-------+-------+-----------+------------------+------------------+-------------------------------------+---|
   | / |   <   |   <   |     <     |        <         |        <         |                  <                  | > |
   |   |   T   |   T   |     T     |        T         |        F         |                  F                  |   |
   |   |   T   |   F   |     F     |        F         |        F         |                  F                  |   |
   |   |   F   |   T   |     T     |        T         |        T         |                  T                  |   |
   |   |   F   |   F   |     F     |        T         |        T         |                  T                  |   |
   |---+-------+-------+-----------+------------------+------------------+-------------------------------------+---|

   Conclusion:

   The column for \(\phi \implies \psi\) (which simplifies \(\phi \implies (\psi \lor 0)\)) and \((\phi \implies \psi) \land (\phi \implies 0)\) are
   identical, proving that \(\phi \implies (\psi \lor 0)\) is equivalent to \((\phi \implies \psi) \land (\phi \implies 0)\).

   The implication \(\phi \implies 0\) will always be false when \(\phi\) is true because a true statement cannot imply a
   false statement. When \(\phi\) is false, the implication \(\phi \implies 0\) is vacuously true because a false statement
   can imply anything.

3. \((\phi \lor \psi) \implies 0\) and \(\phi \implies 0) \land (\psi \implies 0)\)

   Recall that \(\implies 0\) means \(\implies False\), which is equivalent to \(\neg\). So, \((\phi \lor \psi) \implies 0\) means
   \(\neg(\phi \lor \psi)\), which is equivalent to \(\neg\phi \land \neg\psi\). This we need to show.

   |---+-------+-------+-----------+------------------------+------------------+------------------+-------------------------------------+---|
   |   |  <c>  |  <c>  |    <c>    |          <c>           |       <c>        |       <c>        |                 <c>                 |   |
   |   | \(\phi\) | \(\psi\) | \(\phi \lor \psi\) | \((\phi \lor \psi) \implies 0\) | \(\phi \implies 0\) | \(\psi \implies 0\) | \((\phi \implies 0) \land (\psi \implies 0)\) |   |
   |---+-------+-------+-----------+------------------------+------------------+------------------+-------------------------------------+---|
   | / |   <   |   <   |     <     |           <            |        <         |        <         |                  <                  | > |
   |   |   T   |   T   |     T     |           F            |        F         |        F         |                  F                  |   |
   |   |   T   |   F   |     T     |           F            |        F         |        T         |                  F                  |   |
   |   |   F   |   T   |     T     |           F            |        T         |        F         |                  F                  |   |
   |   |   F   |   F   |     F     |           T            |        T         |        T         |                  T                  |   |
   |---+-------+-------+-----------+------------------------+------------------+------------------+-------------------------------------+---|

   Conclusion:

   The implication \((\phi \lor \psi) \implies 0\) will always be false when \(\phi \lor \psi\) is true because a true statement cannot
   imply a false statement. When \(\phi \lor \psi\) is false, the implication \((\phi \lor \psi) \implies 0\) is vacuously true because a
   false statement can imply anything.

   The column for \((\phi \lor \psi) \implies 0\) and \((\phi \implies 0) \land (\psi \implies 0\) are identical, proving that \((\phi \lor \psi)
   \implies 0\) is equivalent to \((\phi \implies 0) \land (\psi \implies 0)\).

** Assignment 4 - Part 9B

Use truth tables to prove that the following are equivalent:

1. \(\phi \implies (\psi \lor \theta)\) and \((\phi \implies \psi) \land (\phi \implies \theta)\)

2. \((\phi \lor \psi) \implies \theta\) and \(\phi \implies \theta) \land (\psi \implies \theta)\)

*A*:

When we constructing truth tables with three proposition \(\phi, \psi, \theta\), there are
\(2^3 = 8\) possible combinations of truth values, not just 4. Here


1. \(\phi \implies (\psi \lor \theta)\) and \((\phi \implies \psi) \land (\phi \implies \theta)\)

   Truth table for \(\phi \implies (\psi \lor \theta)\)

   |---+-------+-------+-------+-----------+------------------------+---|
   |   |  <c>  |  <c>  |  <c>  |    <c>    |          <c>           |   |
   |   | \(\phi\) | \(\psi\) | \(\theta\) | \(\psi \lor \theta\) | \(\phi \implies (\psi \lor \theta)\) |   |
   |---+-------+-------+-------+-----------+------------------------+---|
   | / |   <   |   <   |   <   |     <     |           <            | > |
   |   |   T   |   T   |   T   |     T     |           T            |   |
   |   |   T   |   T   |   F   |     T     |           T            |   |
   |   |   T   |   F   |   T   |     T     |           T            |   |
   |   |   T   |   F   |   F   |     F     |           F            |   |
   |   |   F   |   T   |   T   |     T     |           T            |   |
   |   |   F   |   T   |   F   |     T     |           T            |   |
   |   |   F   |   F   |   T   |     T     |           T            |   |
   |   |   F   |   F   |   F   |     F     |           T            |   |
   |---+-------+-------+-------+-----------+------------------------+---|

   Truth table for \((\phi \implies \psi) \land (\phi \implies \theta)\)

   |---+-------+-------+-------+------------------+------------------+-------------------------------------+---|
   |   |  <c>  |  <c>  |  <c>  |       <c>        |       <c>        |                 <c>                 |   |
   |   | \(\phi\) | \(\psi\) | \(\theta\) | \(\phi \implies \psi\) | \(\phi \implies \theta\) | \((\phi \implies \psi) \land (\phi \implies \theta)\) |   |
   |---+-------+-------+-------+------------------+------------------+-------------------------------------+---|
   | / |   <   |   <   |   <   |        <         |        <         |                  <                  | > |
   |   |   T   |   T   |   T   |        T         |        T         |                  T                  |   |
   |   |   T   |   T   |   F   |        T         |        T         |                  F                  |   |
   |   |   T   |   F   |   T   |        T         |        T         |                  F                  |   |
   |   |   T   |   F   |   F   |        F         |        F         |                  F                  |   |
   |   |   F   |   T   |   T   |        T         |        T         |                  T                  |   |
   |   |   F   |   T   |   F   |        T         |        T         |                  T                  |   |
   |   |   F   |   F   |   T   |        T         |        T         |                  T                  |   |
   |   |   F   |   F   |   F   |        F         |        T         |                  T                  |   |
   |---+-------+-------+-------+------------------+------------------+-------------------------------------+---|

   Combine \(\phi \implies (\psi \lor \theta)\) and \((\phi \implies \psi) \land (\phi \implies \theta)\)

   |---+-------+-------+-------+------------------------+-------------------------------------+---|
   |   |  <c>  |  <c>  |  <c>  |          <c>           |                 <c>                 |   |
   |   | \(\phi\) | \(\psi\) | \(\theta\) | \(\phi \implies (\psi \lor \theta)\) | \((\phi \implies \psi) \land (\phi \implies \theta)\) |   |
   |---+-------+-------+-------+------------------------+-------------------------------------+---|
   | / |   <   |   <   |   <   |           <            |                  <                  | > |
   |   |   T   |   T   |   T   |           T            |                  T                  |   |
   |   |   T   |   T   |   F   |           T            |                  F                  |   |
   |   |   T   |   F   |   T   |           T            |                  F                  |   |
   |   |   T   |   F   |   F   |           F            |                  F                  |   |
   |   |   F   |   T   |   T   |           T            |                  T                  |   |
   |   |   F   |   T   |   F   |           T            |                  T                  |   |
   |   |   F   |   F   |   T   |           T            |                  T                  |   |
   |   |   F   |   F   |   F   |           T            |                  T                  |   |
   |---+-------+-------+-------+------------------------+-------------------------------------+---|

   Comparing the result from previous two table, we can see they are *not* identical. Specifically:

     - In the row where \(\phi\) is true, and \(\theta\) is false (T, T, F):

         - \(\phi \implies (\psi \lor \theta)\) is true

         - \((\phi \implies \psi) \land (\phi \implies \theta)\) is false.

  This sows that \(\phi \implies (\psi \lor \theta)\) is *not* equivalent to \((\phi \implies \psi) \land (\phi \implies \theta)\). Therefore,

  *Correction: Equivalence to Be Proven*:

  This actual equivalence to be proven is:

  \begin{center}
  \text{\(\phi \implies (\psi \lor \theta) \equiv (\phi \implies \psi) \lor (\phi \implies \theta)\)}
  \end{center}

  Let's construct the truth table for above equivalence:

  Truth Table for \((\phi \implies \psi) \lor (\phi \implies \theta)\)

   |---+-------+-------+-------+------------------+------------------+-------------------------------------+---|
   |   |  <c>  |  <c>  |  <c>  |       <c>        |       <c>        |                 <c>                 |   |
   |   | \(\phi\) | \(\psi\) | \(\theta\) | \(\phi \implies \psi\) | \(\phi \implies \theta\) | \((\phi \implies \psi) \lor (\phi \implies \theta)\) |   |
   |---+-------+-------+-------+------------------+------------------+-------------------------------------+---|
   | / |   <   |   <   |   <   |        <         |        <         |                  <                  | > |
   |   |   T   |   T   |   T   |        T         |        T         |                  T                  |   |
   |   |   T   |   T   |   F   |        T         |        T         |                  T                  |   |
   |   |   T   |   F   |   T   |        T         |        T         |                  T                  |   |
   |   |   T   |   F   |   F   |        F         |        F         |                  F                  |   |
   |   |   F   |   T   |   T   |        T         |        T         |                  T                  |   |
   |   |   F   |   T   |   F   |        T         |        T         |                  T                  |   |
   |   |   F   |   F   |   T   |        T         |        T         |                  T                  |   |
   |   |   F   |   F   |   F   |        F         |        T         |                  T                  |   |
   |---+-------+-------+-------+------------------+------------------+-------------------------------------+---|

  Now comparing the truth tables for \((\phi \implies (\psi \lor \theta)\) and \((\phi \implies \psi) \lor (\phi \implies \theta)\);

   |---+-------+-------+-------+------------------------+-------------------------------------+---|
   |   |  <c>  |  <c>  |  <c>  |          <c>           |                 <c>                 |   |
   |   | \(\phi\) | \(\psi\) | \(\theta\) | \(\phi \implies (\psi \lor \theta)\) | \((\phi \implies \psi) \lor (\phi \implies \theta)\) |   |
   |---+-------+-------+-------+------------------------+-------------------------------------+---|
   | / |   <   |   <   |   <   |           <            |                  <                  | > |
   |   |   T   |   T   |   T   |           T            |                  T                  |   |
   |   |   T   |   T   |   F   |           T            |                  T                  |   |
   |   |   T   |   F   |   T   |           T            |                  T                  |   |
   |   |   T   |   F   |   F   |           F            |                  F                  |   |
   |   |   F   |   T   |   T   |           T            |                  T                  |   |
   |   |   F   |   T   |   F   |           T            |                  T                  |   |
   |   |   F   |   F   |   T   |           T            |                  T                  |   |
   |   |   F   |   F   |   F   |           T            |                  T                  |   |
   |---+-------+-------+-------+------------------------+-------------------------------------+---|

  The columns for \((\phi \implies (\psi \lor \theta)\) and \((\phi \implies \psi) \lor (\phi \implies \theta)\) are now identical, confirming
  equivalence.

2. \((\phi \lor \psi) \implies \theta\) and \(\phi \implies \theta) \land (\psi \implies \theta)\)

   Let's construct the truth table for \((\phi \lor \psi) \implies \theta\) and \((\phi \implies \theta) \land (\psi \implies \theta)\) to verify their
   equivalence:

   Truth Table for \((\phi \lor \psi) \implies \theta\):

   |---+-------+-------+-------+-----------+------------------------+---|
   |   |  <c>  |  <c>  |  <c>  |    <c>    |          <c>           |   |
   |   | \(\phi\) | \(\psi\) | \(\theta\) | \(\phi \lor \psi\) | \((\phi \lor \psi) \implies \theta\) |   |
   |---+-------+-------+-------+-----------+------------------------+---|
   | / |   <   |   <   |   <   |     <     |           <            | > |
   |   |   T   |   T   |   T   |     T     |           T            |   |
   |   |   T   |   T   |   F   |     T     |           F            |   |
   |   |   T   |   F   |   T   |     T     |           T            |   |
   |   |   T   |   F   |   F   |     F     |           F            |   |
   |   |   F   |   T   |   T   |     T     |           T            |   |
   |   |   F   |   T   |   F   |     T     |           F            |   |
   |   |   F   |   F   |   T   |     F     |           T            |   |
   |   |   F   |   F   |   F   |     F     |           T            |   |
   |---+-------+-------+-------+-----------+------------------------+---|

   Truth Table for \((\phi \implies \theta) \land (\psi \implies \theta)\):

   |---+-------+-------+-------+------------------+------------------+-------------------------------------+---|
   |   |  <c>  |  <c>  |  <c>  |       <c>        |       <c>        |                 <c>                 |   |
   |   | \(\phi\) | \(\psi\) | \(\theta\) | \(\phi \implies \theta\) | \(\psi \implies \theta\) | \((\phi \implies \theta) \land (\psi \implies \theta)\) |   |
   |---+-------+-------+-------+------------------+------------------+-------------------------------------+---|
   | / |   <   |   <   |   <   |        <         |        <         |                  <                  | > |
   |   |   T   |   T   |   T   |        T         |        T         |                  T                  |   |
   |   |   T   |   T   |   F   |        F         |        F         |                  F                  |   |
   |   |   T   |   F   |   T   |        T         |        T         |                  T                  |   |
   |   |   T   |   F   |   F   |        F         |        T         |                  F                  |   |
   |   |   F   |   T   |   T   |        T         |        T         |                  T                  |   |
   |   |   F   |   T   |   F   |        T         |        F         |                  F                  |   |
   |   |   F   |   F   |   T   |        T         |        T         |                  T                  |   |
   |   |   F   |   F   |   F   |        T         |        T         |                  T                  |   |
   |---+-------+-------+-------+------------------+------------------+-------------------------------------+---|

   Comparing the two tables:

   |---+-------+-------+-------+------------------------+-------------------------------------+---|
   |   |  <c>  |  <c>  |  <c>  |          <c>           |                 <c>                 |   |
   |   | \(\phi\) | \(\psi\) | \(\theta\) | \((\phi \lor \psi) \implies \theta\) | \((\phi \implies \theta) \land (\psi \implies \theta)\) |   |
   |---+-------+-------+-------+------------------------+-------------------------------------+---|
   | / |   <   |   <   |   <   |           <            |                  <                  | > |
   |   |   T   |   T   |   T   |           T            |                  T                  |   |
   |   |   T   |   T   |   F   |           F            |                  F                  |   |
   |   |   T   |   F   |   T   |           T            |                  T                  |   |
   |   |   T   |   F   |   F   |           F            |                  F                  |   |
   |   |   F   |   T   |   T   |           T            |                  T                  |   |
   |   |   F   |   T   |   F   |           F            |                  F                  |   |
   |   |   F   |   F   |   T   |           T            |                  T                  |   |
   |   |   F   |   F   |   F   |           T            |                  T                  |   |
   |---+-------+-------+-------+------------------------+-------------------------------------+---|

   Upon examining the truth tables, we can see that they are, in fact identical. Each row in the table for \((\phi \lor \psi)
   \implies \theta\) matches exactly with the corresponding row in the table for \((\Phi \implies \theta) \land (\psi \implies \theta)\). This
   indication that logical statements \((\phi \lor \psi) \implies \theta\) and \((\phi \implies \theta) \land (\psi \implies \theta)\) are indeed
   equivalence.

** Assignment 4 - Part 10

Verify the equivalence in the previous question by means of a logical argument. (So, you must show that assuming \(\phi\)
and deducing \(\psi \land 0\) is the same as both deducing \(\psi\) from \(\phi\) and \(0\) from \(\phi\)).

*A*: To verify the equivalency of \(\phi \implies (\psi \land 0)\) and \((\phi \implies \psi) \land (\phi \implies 0)\) using a logical argument,
we need to show that the two expression produce the same result under the same conditions. Let's break down the logical
of each expressions step by step.

*Logical Argument*:

*Expression 1*: \(\phi \implies (\psi \land 0)\)

  - \(\phi \land 0\) is always false because 0 (false) AND anything is false.

  - Therefore, \(\phi \implies (\psi \land 0)\) simplifies to \(\phi \implies False\)

  - The implication \(\phi \implies False\) is true if and only if \(\phi\) is false. If \(\phi\) is true, than the implication is
    false.

*Expression 2*: \((\phi \implies \psi) \land (\phi \implies 0)\)

  - \(\phi \implies \psi\) means that if \(\phi\) is true, then  \(\psi\) must be true.

  - \(\phi \implies 0\) means that if \(\phi\) is true, than 0 (false) must be true, this is contradiction, so \(\phi \implies
    0\) is true if and only if \(\phi\) is false.

  - Therefore, \(\phi \implies \psi) \land (\phi \implies 0)\) is true if and only if \(\phi\) is false. If \(\phi\) is true, than \(\phi
    \implies 0\) is false, making the entire conjunction false.


*Step-by-Step Proof*:

*1.Assume*: \(\phi \implies (\psi \land 0)\)

  - \(\phi \implies (\psi \land 0)\) is equivalent to \(\phi \implies False\)

  - This means that if \(\phi\) is true, then the result must be false.

  - Therefore, \(\phi\) must be false for the implication to hold true.

*2.Assume*: \((\phi \implies \psi) \land (\phi \implies 0)\)

  - \(\phi \implies \psi\) means that if \(\phi\) is true, then \(\psi\) must be true.

  - \(\phi \implies 0\) means that if (\phi\) is true, then 0 (false) must be true, which is contradiction.

  - Therefore, \(\phi\) must be false for \(\phi \implies 0\) to hold true.

  - If \(\phi\) is false, then \(\phi \implies \psi\) is true regardless of (\psi\)


*Conclusion*:

Both expression \(\phi \implies (\phi \land 0)\) and \((\phi \implies \psi) \land (\phi \land 0)\) are true if and only if \(\phi\) is false. If
\(\phi\) is true, both expression are false. Therefore, the two expression are logicallay equivalent.

This logical argument shows that assuming \(\phi\) and deducing \(\psi \land 0\) is the same as both deducing \(\psi\) from \(\phi\) and
\(0\) from \(\phi\)

** Assignment 4 - Part 10A

1. \(\phi \implies (\psi \lor \theta)\) and \((\phi \implies \psi) \land (\phi \implies \theta)\)

2. \((\phi \lor \psi) \implies \theta\) and \(\phi \implies \theta) \land (\psi \implies \theta)\)

Verify the equivalence in the above equation by means of a logical argument. (So, in the case of \(\phi \implies (\psi \lor \theta)\)
and \((\phi \implies \psi) \land (\phi \implies \theta)\) for example, you must show that assuming \(\phi\) and deducing \(\psi \land \theta\) is the
same as both deducing \(\psi\) from \(\phi\) and \(\theta\) from \(\phi\)).

Let's start by verifying the equivalence of each pair statement using logical arguments.

1. \(\phi \implies (\psi \lor \theta)\) and \((\phi \implies \psi) \land (\phi \implies \theta)\)

   *Logical Argument*

   *Step-1: Assume \(\phi\) and deduce \(\psi \lor \theta\)*

   Given \(\phi \implies (\psi \lor \theta)\), if \(\phi\) is true, then \(\psi \lor \theta\) must be true.

   *Step-2: Assume \(\phi\) and deduce \(\psi\)*

   Given \(\phi \implies \psi\), if \(\phi\) is true, then \(\psi\) must be true.

   *Step-3: Assume \(\phi\) and deduce \(\theta\)*

   Given \(\phi \implies \theta\), if \(\phi\) is true, then \(\theta\) must be true.

   We need to show that assuming \(\phi\) and deducing \(\psi \lor \theta\) is the same as both deducing \(\psi\) from \(\phi\) and \(\theta\)
   from \(\phi\).

     - If \(\phi \implies (\psi \lor \theta)\) is true:

       - \(\phi\) implies \(\psi \lor \theta\)

       - Therefore, if \(\phi\) is true, either \(\psi\) or \(\theta\) must be true, satisfying \(\psi \lor \theta\).

     - If \((\phi \implies \psi) \land (\psi \lor \theta)\) is true:

       - \(\phi\) implies \(\psi\)

       - \(phi\) implies \(\theta\)

       - Therefore, if \(\phi\) is true, both \(\psi\) and \(\theta\) must be true.

2. \((\phi \lor \psi) \implies \theta\) and \(\phi \implies \theta) \land (\psi \implies \theta)\)

   *Logical Argument*

   *Step-1: Assume \(\phi \lor \psi\) and deduce \(\theta\)*

   Given \((\phi \lor \psi) \implies \theta\), if \(\phi \lor \psi\) is true, then \(\theta\) must be true.

   *Step-2: Assume \(\psi\) and deduce \(\theta\)*

   Given \(\psi \implies \theta\), if \(\psi\) is true, then \(\theta\) must be true.

   We need to show that assuming \(\phi \lor \psi\) and deducing \(\theta\) is the same both deducing \(\theta\) from \(\phi\) and \(\theta\) from
   \(\psi\).

     - If \((\phi \lor \psi) \implies \theta\) is true:

       - \(\phi \lor \psi\) implies \(\theta\)

       - Therefore, if either \(\phi\) or \(\psi\) is true, \(\theta\) must be true.

     - If \((\phi \implies \theta) \land (\psi \implies \theta\) is true:

       - \(\phi\) implies \(theta\)

       - \(\psi\) implies \(\theta\)

       - Therefore, if either \(\phi\) or \(\psi\) is true, \(\theta\) must be true.

 Thus, \((\phi \lor \psi) \implies \theta\) is equivalent to \((\phi \implies \theta) \land (\psi \implies \theta)\).

 *Summary With Equations*

   1. \(\phi \implies (\psi \lor \theta)\) is equivalent to \((\phi \implies \psi) \land (\phi \implies \theta)\)

   2. \((\phi \lor \psi) \implies \theta\) is equivalent to \((\phi \implies \theta) \land (\psi \implies \theta)\)

   In both cases, the logical equivalence is demonstrated by showing that the assumed conditions lead to the same
   conclusion in both direction.

** Assignment 4 - Part 11

Use truth tables to prove the equivalence of \(\phi \implies \psi\) and \((\neg\psi) \implies (\neg\phi)\).

\((\neg\psi) \implies (\neg\phi)\) is called /contrapositive/ of \(\phi \implies \psi\). The logical equivalence of a conditional and its
contrapositive means that one way to prove an implication it is to verify the contrapositive. This is a common form of
proof in mathematics that we'll encouter later.

*A* To prove the equivalence of \(\phi \implies \psi\) and \((\neg\psi) \implies (\neg\phi)\) using truth tables, we need to construct the truth
tables for both expression and compare the results.

*Truth Table for* \(\phi \implies \psi\):

The implication \(\phi \implies \psi\) is false only when \(\phi\) is true and \(\psi\) is false. In all other cases, it is true.

|---+-------+-------+------------------+---|
|   |  <c>  |  <c>  |       <c>        |   |
|   | \(\phi\) | \(\psi\) | \(\phi \implies \psi\) |   |
|---+-------+-------+------------------+---|
| / |   <   |   <   |        <         | > |
|   |   T   |   T   |        T         |   |
|   |   T   |   F   |        F         |   |
|   |   F   |   T   |        T         |   |
|   |   F   |   F   |        T         |   |
|---+-------+-------+------------------+---|


*Truth Table for* \(\neg\phi) \implies (\neg\psi)\):

The contrapositive \((\neg\phi) \implies (\neg\psi)\) is false only when \(\neg\psi\) is true, and \(\neg\phi\) is false, which means \(\psi\) is
false and \(\phi\) is true. In all other cases, it is true.

|---+-------+-------+--------+-------+-----------------------+---|
|   |  <c>  |  <c>  |  <c>   |  <c>  |          <c>          |   |
|   | \(\phi\) | \(\psi\) | \(\neg\phi\) | \(\neg\psi) | \(\neg\phi) \implies (\neg\psi)\) |   |
|---+-------+-------+--------+-------+-----------------------+---|
| / |   <   |   <   |   <    |   <   |           <           | > |
|   |   T   |   T   |   F    |   F   |           T           |   |
|   |   T   |   F   |   F    |   T   |           F           |   |
|   |   F   |   T   |   T    |   F   |           T           |   |
|   |   F   |   F   |   T    |   T   |           T           |   |
|---+-------+-------+--------+-------+-----------------------+---|

*Comparison of the Truth Tables*:

|---+-------+-------+------------------+-----------------------+---|
|   |  <c>  |  <c>  |       <c>        |          <c>          |   |
|   | \(\phi\) | \(\psi\) | \(\phi \implies \psi\) | \(\neg\phi) \implies (\neg\psi)\) |   |
|---+-------+-------+------------------+-----------------------+---|
| / |   <   |   <   |        <         |           <           | > |
|   |   T   |   T   |        T         |           T           |   |
|   |   T   |   F   |        F         |           F           |   |
|   |   F   |   T   |        T         |           T           |   |
|   |   F   |   F   |        T         |           T           |   |
|---+-------+-------+------------------+-----------------------+---|

*Conclusion*:

The truth tables for \(\phi \implies \psi\) and \(\neg\phi) \implies (\neg\psi)\) are identical. For each combination of \(\phi\) and \(\psi\),
the truth values of the two expression match exactly.

This we have, proven using truth tables that \(\phi \implies \psi\) and \(\neg\phi) \implies (\neg\psi)\). This logical equivalence is
known as the *contrapositive*, and it is powerful tool in mathematical proofs. By proofing the contrapositive, we can
verify the validity of an implication.

** Assignment 4 - Part 12

*Q* Write down the contrapositive of the following statements:

  1. If two rectangles are [fn:6]congruent, they have the same area.

  2. If a triangle with sides a, b, c (c largest) is right-angled, then \(a^2 + b^2 = c^2\).

  3. If \(2^n - 1\)  is prime, then \(n\) is prime.

  4. If the Yuan rises, the Dollar will fall.

*A* To write down the contrapositive of each statement, we will first identify the hypothesis \((p)\) and the conclusion
\(q)\) in the form of \(\phi \implies \psi\). The contrapositive of \(\phi \implies \psi\) is \(\neg\psi \implies \neg\phi\).

  1. If two rectangles are congruent, they have the same area.

     - Original statement: If two rectangles are congruent, they have the same area.

        - Hypothesis \((\phi)\): Two rectangles are congruent.

        - Conclusion \((\psi)\): They have the same area.

     - Contrapositive: If two rectangles do not have the same area, they are not congruent.

        - \(\neg\psi \implies \neg\phi\): If two rectangles do not have the same area, the are not congruent.

  2. If a triangle with sides a, b, c (c largest) is right-angled, then \(a^2 + b^2 = c^2\).

     - Original statement: If a triangle with sides a, b, c (c largest) is right-angled, then \(a^2 + b^2 = c^2\).

        - Hypothesis \((\phi)\): A triangle with sides \(a, b, c\), (\(c\) is largest) is not right-angled.

        - Conclusion \((\psi)\): \(a^2 + b^2 = c^2\)

    - Contrapositive: If \(a^2 + b^2 \ne c^2\), then the triangle with sides \(a, b, c\) (\(c\) largest) is not
      right-angled.

       - \(\neg\psi \implies \neg\phi\): If \(a^2 + b^2 \ne c^2\), then the triangle with sides \(a, b, c\) (\(c\) largest) is not
          right-angled.

  3. If \(2^n - 1\)  is prime, then \(n\) is prime.

     - Original statement: If \(2^n - 1\)  is prime, then \(n\) is prime.

       - Hypothesis \((\phi)\): If \(2^n - 1\)  is prime

       - Conclusion \((\psi)\): \(n\) is prime.

     - Contrapositive: if \(n\) is not prime number, then \(2^n - 1\) is not prime.

        - \(\neg\psi \implies \neg\phi\): if \(n\) is not prime number, then \(2^n - 1\) is not prime.

  4. If the Yuan rises, the Dollar will fall.

     - original statement: If the Yuan rises, the Dollar will fall.

       - Hypothesis \((\phi)\): The Yuan rises

       - Conclusion \((\psi)\): Dollar will fall.

     - Contrapositive: If the Dollar does not fall, the Yuan will not rise.

       - \(\neg\psi \implies \neg\phi\): If the Dollar does not fall, the Yuan will not rise.

** Assignment 4 - Part 13

*Q* It is important not to confuse the contrapositive of a conditional \(\phi \implies \psi\) with is /converse/ \(\psi \implies
\phi\). Use truth tables to show that the contrapositive and the converse of \(\phi \implies \psi\) are not equivalent.

*A* To demonsrate that the contrapositive and the converse of \(\phi \implies \psi\) are not equivalent, we can construct truth tables
for both the contrapositive \((\neg\phi) \implies (\neg\psi)\) and the converse  \(\psi \implies \phi\). We will then compare the truth values.

Truth Table for \(\phi \implies \psi\)

|---+-------+------+------------------+---|
|   |  <c>  | <c>  |       <c>        |   |
|   | \(\phi\) | \(\psi) | \(\phi \implies \psi\) |   |
|---+-------+------+------------------+---|
| / |   <   |  <   |        <         | > |
|   |   T   |  T   |        T         |   |
|   |   T   |  F   |        F         |   |
|   |   F   |  T   |        T         |   |
|   |   F   |  F   |        T         |   |
|---+-------+------+------------------+---|


Truth Table for Contrapositive \(\neg\psi) \implies \(\neg\phi)\)

|---+-------+------+--------+--------+------------------------+---|
|   |  <c>  | <c>  |  <c>   |  <c>   |          <c>           |   |
|   | \(\phi\) | \(\psi) | \(\neg\psi\) | \(\neg\phi\) | \((\neg\psi) \implies (\neg\phi)\) |   |
|---+-------+------+--------+--------+------------------------+---|
| / |   <   |  <   |   <    |   <    |           <            | > |
|   |   T   |  T   |   F    |   F    |           T            |   |
|   |   T   |  F   |   T    |   F    |           F            |   |
|   |   F   |  T   |   F    |   T    |           T            |   |
|   |   F   |  F   |   T    |   T    |           T            |   |
|---+-------+------+--------+--------+------------------------+---|

Truth Table for Converse \(\psi \implies \phi\)

|---+-------+------+------------------+---|
|   |  <c>  | <c>  |       <c>        |   |
|   | \(\phi\) | \(\psi) | \(\psi \implies \phi\) |   |
|---+-------+------+------------------+---|
| / |   <   |  <   |        <         | > |
|   |   T   |  T   |        T         |   |
|   |   T   |  F   |        T         |   |
|   |   F   |  T   |        F         |   |
|   |   F   |  F   |        T         |   |
|---+-------+------+------------------+---|

Comparing Truth Values:

from the truth tables, we see that:

- For the original implication \(\phi \implies \psi\)

  - \(\phi = T, \psi = T\) result in \(T\)
  - \(\phi = T, \psi = F\) result in \(F\)
  - \(\phi = F, \psi = T\) result in \(T\)
  - \(\phi = F, \psi = F\) result in \(T\)

- For the contrapositive \((\neg\psi) \implies (\neg\phi)\)

  - \(\phi = T, \psi = T\) result in \(T\)
  - \(\phi = T, \psi = F\) result in \(F\)
  - \(\phi = F, \psi = T\) result in \(T\)
  - \(\phi = F, \psi = F\) result in \(T\)

- For the converse \(\psi \implies \phi\)

  - \(\phi = T, \psi = T\) result in \(T\)
  - \(\phi = T, \psi = F\) result in \(T\)
  - \(\phi = F, \psi = T\) result in \(F\)
  - \(\phi = F, \psi = F\) result in \(T\)


The truth values for the contrapositive \((\neg\psi) \implies (\neg\phi)\) match exactly with the original implication \(\phi \implies
\psi\), demonstrating that they are equivalent. However, the truth values for the converse \(\psi \implies \phi\) do not matching
with the original \(\phi \implies \psi\), showing that the converse is not equivalent to the original implication.

Thus, the contrapositive and the converse of \(\phi \implies \psi\) are not equivalent.

** Assignment 4 - Part 14

*Q* Write down the converse of the four statement in question 12.

*A*:

1. If two rectangles are congruent, they have the same area.

   - Original Statement: If two rectangles are congruent, they have the same area.

     - \(\phi\): Two rectangles are congruent.

     - \(\psi\): They have the same area.

     - Conditional: \(\phi \implies \psi\).

   - Converse: If two rectangles have the same area, they are congruent.

     - Conditional: \(\psi \implies \phi\).

   - Contrapositive: If two rectangles do not have the same area, they are not congruent.

     - Conditional: \(\neg\psi) \implies (\neg\phi)\).

2. If a triangle with sides a, b, c (c largest) is right-angled, then \(a^2 + b^2 = c^2\).

   - Original Statement: If a triangle with sides a, b, c (c largest) is right-angled, then \(a^2 + b^2 = c^2\).

     - \(\phi\): A triangle with sides a, b, c (c largest) is right-angled.

     - \(\psi\): \(a^2 + b^2 = c^2\).

     - Conditional: \(\phi \implies \psi\)

   - Converse: If \(a^2 + b^2 = c^2\), then a triangle with a sides \(a, b, c\) (\(c\) largest) is right angled.

     - Conditional: \(\psi \implies \phi\)

   - Contrapositive: If \(a^2 + b^2 \ne c^2\), then a triangle with a sides \(a, b, c\) (\(c\) largest) is right angled.

     - Conditional: \(\neg\psi) \implies (\neg\phi)\)

3. If \(2^n - 1\)  is prime, then \(n\) is prime.

   - Original Statement: If \(2^n - 1\)  is prime, then \(n\) is prime.

     - \(\phi\): \(2^n - 1\)  is prime.

     - \(\psi\): \(n\) is prime.

     - Conditional: \(\phi \implies \psi\).

   - Converse: If \(n\) is prime, then \(2^n - 1\) is prime.

     - Conditional: \(\psi \implies \phi\).

   - Contrapositive: If \(n\) is not prime, then \(2^n - 1\) is not prime.

     - Conditional: \(\neg\phi) \implies (\neg\psi)\).

4. If the Yuan rises, the Dollar will fall.

   - Original Statement: If the Yuan rises, the Dollar will fall.

     - \(\phi\): The Yuan rises.

     - \(\psi\): The Dollar will fall.

     - Conditional: \(\phi \implies \psi\)

   - Converse: If the Dollar fail, the Yuan will rise.

     - Conditional: \(\psi \implies \phi\)

   - Contrapositive: If the Dollar does not fail, the Yuan will not rise.

     - Conditional: \(\neg\psi) \implies (\neg\phi)\).

* Problem Set 2

This problem set focuses on material covered in Lectures-III and IV, so I recommend you to watch both lectures and attempt
Assignment 3 and 4 before submitting your answers

** Problem Set 2 - Part 1

*Q* Which of the following condition are /necessary/ for the natural number \(n\) to be divisible by 6? Select all those
you believe are necessary:

  (a) \(n\) is divisible by 3.

  (b) \(n\) is divisible by 9.

  (c) \(n\) is divisible by 12.

  (d) \(n\) = 24.

  (e) \(n^2\) is divisible by 3.

  (f) \(n\) is even and divisible by 3.

*A* In summary, the necessary condition for a natural number \(n\) to be divisible by 6 are:

(a) \(n\) is divisible by 3.

(f) \(n\) is even and divisible by 3.

Here's why:

  - (a): If \(n\) divisible by 3, then \(n\) is also divisible by 6. This is because \(6 = 2 X 3\), and if \(n\) is
    divisible by 3, then it also divisible by 2 (since it is even).

  - (f): If \(n\) is even and divisible by 3, then \(n\) is divisible by 6. This is because \(6 = 2 X 3\), and if \(n\)
    is even and divisible by 3, then it is divisible by 2 and 3, which means it is divisible by 6.

The other option:

  - (b): \(n\) being divisible by 9 is not necessary condition for it to be divisible by 6. For example, 12 is divisible
    by 6 but not by 9.

  - (c): \(n\) being divisible by 12 is not necessary condition for it to be divisible by 6. While 12 is a multiple of 6,
    it is not a requirement for divisibility by 6. For example, the number 18 is divisible by 6 but not divisible by 12.


  - (d) \(n\) = 24, This statement is sufficient for \(n\) to be divisible by 6, but is not necessary. If \(n = 24\), it
    is divisible by 6. However, there are other numbers that are divisible by 6 without being equal to 24, such as 12,
    18, or 30.

  - (e) \(n^2\) is divisible by 3. This statement is not necessary for \(n\) to be divisible by 6. The divisibility of
    \(n^2\) by 3 does not guarantee that \(n\) itself is divisible by 6. For example, if \(n = 9\) then \(n^2 = 81\),
    which is divisible by 3, but 9 is not divisible by 6.

** Problem Set 2 - Part 2

*Q* Which of the following condition are /sufficient/ for the natural number \(n\) to be divisible by 6? Select all those
you believe are necessary:

  (a) \(n\) is divisible by 3.

  (b) \(n\) is divisible by 9.

  (c) \(n\) is divisible by 12.

  (d) \(n\) = 24.

  (e) \(n^2\) is divisible by 3.

  (f) \(n\) is even and divisible by 3.

  *A* To determine which conditions are sufficient for a natural number \(n\) to be divisible by 6, we need to remember that a number
  is divisible by 6 if and only if it is divisible by both 2 and 3.

  The condition that are sufficient for natural number, \(n\) to be divisible by 6 are follows:

  (c) \(n\) divisible by 12

    - Example: \(n\) = 24. Since 24 is divisible by 12, it is also divisible by 6.

  (d) \(n\) = 24

    - Example: \(n\) = 25. This is self-explanatory as 24 is divisible by 6.

  (f) \(n\) is even and divisible by 3

    - Example: \(n\) = 18. Since 18 is even and divisible by 3, it meets both criteria and is therefore divisible by 6.

** Problem Set 2 - Part 3

*Q* Which of the following condition are /necessary/ and /sufficient/ for the natural number \(n\) to be divisible by 6?
Select all those you believe are necessary and sufficient, give all the example and explanation:

  (a) \(n\) is divisible by 3.

  (b) \(n\) is divisible by 9.

  (c) \(n\) is divisible by 12.

  (d) \(n\) = 24.

  (e) \(n^2\) is divisible by 3.

  (f) \(n\) is even and divisible by 3.

*A* To determine which conditions are both necessary and sufficient for the natural number \(n\) to be divisible by 6,
we need to identify conditions that must hold true for \(n\) to be divisible by 6 and that are also enough to guarantee
divisibility by 6.

*Necessary and Sufficient Conditions*:

  (f) \(n\) is even and divisible by 3.

    - Necessary: If \(n\) is divisible by 6, it must be both even and divisible by 3,

    - Sufficient: If \(n\) is even and divisible by 3, it will be divisible by 6.

    - Example: \(n = 18\). Since 18 is even and divisible by 3, it is divisible by 6.

*Other Condition*:

  (a) \(n\) divisible by 3.

    - Not Sufficient: \(n\) also needs to be even.

    - Not Necessary: Being divisible by 3 alone does not ensure \(n\) is divisible by 6.

    - Example: \(n = 9\) is divisible by 3 but not by 6.

  (b) \(n\) divisible by 9.

    - Not Sufficient: \(n\) must also be even.

    - Not Necessary: \(n\) can be divisible by 6 without being divisible by 9.

    - Example: \(n = 9\) is divisible by 3 but not by 6.

  (c) \(n\) divisible by 12.

    - Sufficient: If \(n\) divisible by 12, it will also divisible by 6.

    - Not Necessary: \(n\) does not need to be divisible by 12 to be divisible by 6.

    - Example: \(n = 12\). Since 12 is divisible by 12, it also divisible by 6.

  (d) \(n = 24\)

    - Sufficient: 24 is divisible by 6.

    - Not Necessary: The specific value 24 is not needed for \(n\) to be divisible by 6.

    - Example: \(n = 24\). Since 24 is divisible by 6, it is satisfies the condition.

  (e) \(n^2\) is divisible by 3.

    - Not Sufficient: \(n\) must also be even.

    - Not Necessary: Being divisible by 3 alone does not ensure \(n\) is divisible by 6.

    - Example: \(n = 9\). Since \(9^2 = 81\) it is divisible by 3, but 9 is not divisible by 6.

** Problem Set 2 - Part 4

Identify the antecedent and in the conditional "If the apples are red, they are ready to eat".

*THE APPLES ARE RED* \hspace{0.2in} *THE APPLES ARE READY TO EAT*

*A*:

  - Antecedent: The apples are red

  - Conditional: The apples are ready to eat

In logical form:

  - If (the apples are red) \(implies\) (they are ready to eat).

** Problem Set 2 - Part 5

Identify the antecedent and in the conditional "The differentiability of a function \(f\) is sufficient for \(f\) to be continuous."

*\(f\) IS DIFFERENTIABLE* \hspace{0.2in} *\(f\) is CONTINUOUS*

*A*:

  - Antecedent: \(f\) is differentiable

  - Conditional: \(f\) is continuous.

Rewritten statement:

  - "If \(f\) is differentiable (antecedent), then \(f\) is continuous (consequent)."

In logical form:

  - \(f\) is differentiable \(\implies\) \(f\) is continuous.

** Problem Set 2 - Part 6

Identify the antecedent and in the conditional "A function \(f\) is bounded if \(f\) is integrable"

*\(f\) IS BOUNDED* \hspace{0.2in} *\(f\) IS INTEGRABLE*

*A*:

  - Antecedent: \(f\) is integrable

  - Conditional: \(f\) is bounded

Rewritten statement:

  - "If \(f\) is integrable (antecedent), then \(f\) is bounded (consequent)."

In logical form:

  - \(f\) is integrable \(\implies\) \(f\) is bounded.

** Problem Set 2 - Part 7

Identify the antecedent and in the conditional "A sequence \(S\) is bounded whenever \(S\) is convergent"

*\(S\) IS BOUNDED* \hspace{0.2in} *\(S\) IS CONVERGENT*

*A*:

  - Antecedent: S is convergent

  - Conditional: S is bounded

Rewritten statement:

  - "If \(S\) is convergent (antecedent), then \(S\) is bounded"

In logical form:

  - \(S\) is convergent \(\implies\) \(S\) is bounded.

** Problem Set 2 - Part 8

Identify the antecedent and in the conditional "It is necessary that \(n\) is prime in order for \(2^n - 1\) to be
prime"

*\(n\) IS PRIME* \hspace{0.2in} *\(2^n - 1\) IS PRIME*

*A*:

  - Antecedent: \(2^n - 1\) is prime

  - Conditional: \(n\) is prime

Rewritten statement:

   - "If (\2^n - 1\) is prime (antecedent), then \(n\) is prime (consequent)".

In logical form:

  - \(2^n - 1\) is prime \(\implies\) \(n\) is prime.

** Problem Set 2 - Part 9

Identify the antecedent and in the conditional "The team wins only when Karl is playing"

*THE TEAM WINS* \hspace{0.2in} *KARL IS PLAYING*

*A*:

The antecedent is the condition that must be met for the consequent occur.

The consequent is the result or outcome that follows from the antecedent.

  - Antecedent: Karl is playing

  - Consequent: The teams wins

So the conditional statement can be rewritten as:

  - "If the team wins, then Karl is playing."

In logical form:

  - Symbolic: Team wins \(\implies\) Karl is playing

** Problem Set 2 - Part 10

Identify the antecedent and in the conditional "when Karl plays the team wins"

*THE TEAM WINS* \hspace{0.2in} *KARL IS PLAYING*

*A*:

The antecedent is the condition that must be met for the consequent occur.

The consequent is the result or outcome that follows from the antecedent.

  - Antecedent: Karl is playing

  - Consequent: The team wins

So the conditional statement can be rewritten as:

  - "If Karl plays, then the team wins."

In logical form:

  - Symbolic: Karl is playing \(\implies\) The teams wins.

** Problem Set 2 - Part 11

Identify the antecedent and in the conditional "The team wins when Karl is playing"

*THE TEAM WINS* \hspace{0.2in} *KARL IS PLAYING*

*A*:

The antecedent is the condition that must be met for the consequent occur.

The consequent is the result or outcome that follows from the antecedent.

  - Antecedent: Karl is playing

  - Consequent: The team wins.

So the conditional statement can be rewritten as:

  - "If Karl is playing, then the team wins."

In logical form:

  - Symbolic: Karl is playing \(\implies\) The teams wins.

** Problem Set 2 - Part 12

*Q* For natural number \(m, n\), is it true than \(mn\) is even iff \(m\) and \(n\) are even?

*A*: A number is even if it can be written as 2 times some integer and it can be divided by 2 without leaving a
remainder. this is the definition we use in mathematics. For example:

  - The number 4 is even because it can be written as \(2 X 2\)

  - The number 10 is even because it can be written as \(2 X 5\)

*Examples wit Variables*:

If we let \(m\) and \(n\) be even numbers, we can write:

  - \(m = 2k\), where \(k\) is an integer

  - \(n = 2l\), where \(l\) is an integer.

Here, \(k\) and \(l\) represent any integer values.

*Calculating the Product \(mn\)*:

Now, let's calculate the product \(mn\):

  - \(m X n = (2k) x (2l) = 2 x k x 2 x l = 4kl\)

Here's why:

  - \(m\) is \(2k\) (since \(m\) is even).

  - \(n\) is \(2l\) (since \(n\) is even).

*Resulting Product*:

The product \(mn = 4kl\)

  - \(4kl\) is clearly divisible by 2, which makes \(mn\) an even number.

*Truth Table Revisited*:

|---+-------------------------+-------------------------+-----------------------------------------------+----------------------------+---|
|   |           <c>           |           <c>           |                      <c>                      |            <c>             |   |
|   | \(m\) is even \((E_m)\) | \(n\) is even \((E_n)\) | Both \(m\) and \(n\) are even \((E_m \land E_n)\) | \(mn\) is even \((E_m_n )\) |   |
|---+-------------------------+-------------------------+-----------------------------------------------+----------------------------+---|
| / |            <            |            <            |                       <                       |             <              | > |
|   |            T            |            T            |                       T                       |             T              |   |
|   |            T            |            F            |                       F                       |             T              |   |
|   |            F            |            T            |                       F                       |             T              |   |
|   |            F            |            F            |                       F                       |             F              |   |
|---+-------------------------+-------------------------+-----------------------------------------------+----------------------------+---|

|---+----------------------------+---|
|   |            <c>             |   |
|   | \(E_m_n \iff (E_m \land E_n)\) |   |
|---+----------------------------+---|
| / |             <              | > |
|   |             T              |   |
|   |             F              |   |
|   |             F              |   |
|   |             T              |   |
|---+----------------------------+---|

*Explanation of the Truth Table*:

  - First Row: Both \(m\) and \(n\) are even. The product \(mn\) is even.

    logical form:

      - \(E_m_n \iff (E_m \land E_n)\) is true.

  - Second Row: \(m\) is even, \(n\) is odd. The product \(mn\) is even.

    logical form:

      - \(E_m_n \iff (E_m \land E_n)\) is false.

  - Third Row: \(m\) is odd, \(n\) is even, the product \(mn\) is even.

    logical form:

      - \(E_m_n \iff (E_m \land E_n)\) is false.

  - Fourth Row: Both \(m\) and \(n\) are odd. The product \(mn\) is odd.

      - \(E_m_n \iff (E_m \land E_n)\) is true.

From the truth table, we see that \(E_m_n \iff (E_m \land E_n)\) is not true in all cases. This confirms that the statement
"\(mn\) is even if and only iff both \(m\) and \(n\) are even" is false. The correct statement is "\(mn\) is even if at
least one of \(m\) or \(n\) is even".

** Problem Set 2 - Part 13

*Q* Is it true than \(mn\) is odd iff \(m\) and \(n\) are odd?

*A* Yes, the statement "\(mn\) is odd if and only if \(m\) and \(n\) are odd" is true. Here's the reasoning and proof
using a truth table.

*Proof*:

forward Direction:

If \(m\) and \(n\) are both odd, then \(mn\) is odd.

  - let \(m = 2a + 1\) and \(n = 2b + 1\) where \(a\) and \(b\) are integers (since \(m\) and \(n\) are odd).

  - Then \(mn = (2a + 1) (2b + 1) = 4ab + 2a + 2b + 1 = 2(2ab + a + b) + 1\).

  - \(2(2ab + a + b) + 1\) is clearly of the form \(2k + 1\) where \(k = 2ab + a + b\), hence \(mn\) is odd.

Reserve Direction:

If \(mn\) is odd, then both \(m\) and \(n\) must be odd.

  - Suppose \(mn\) is odd.

  - If either \(m\) \(n\) were even, \(mn\) would be even (since an even number multiplied by any other number is even).

  - Therefore, for \(mn\) to be odd, both \(m\) and \(n\) must be odd.

*Truth Tables*

Let's construct a truth table to illustrate this.

|---+------------------------+------------------------+----------------------------------------------+---------------------------+---|
|   |          <c>           |          <c>           |                     <c>                      |            <c>            |   |
|   | \(m\) is odd \((O_m)\) | \(n\) is odd \((O_n)\) | Both \(m\) and \(n\) are odd \((O_m \land O_n)\) | \(mn\) is odd \((O_m_n\)) |   |
|---+------------------------+------------------------+----------------------------------------------+---------------------------+---|
| / |           <            |           <            |                      <                       |             <             | > |
|   |           T            |           T            |                      T                       |             T             |   |
|   |           T            |           F            |                      F                       |             F             |   |
|   |           F            |           T            |                      F                       |             F             |   |
|   |           F            |           F            |                      F                       |             F             |   |
|---+------------------------+------------------------+----------------------------------------------+---------------------------+---|

*Explanation of the Truth Table*:

  - First Row: Both \(m\) and \(n\) are odd. The product \(mn\) is odd.

  - Second Row: \(m\) is odd, \(n\) is even. the product \(mn\) is even.

  - Third Row: \(m\) is even, \(n\) is odd. The product \(mn\) is even.

  - Fourth Row: Both \(m\) and \(n\) are even. The product \(mn\) is even.

*Conclusion*:

The truth table confirms that \(mn\) is odd if and only if both \(mn\) are odd. This means that the statement "\(mn\) is
odd iff \(m\) and \(n\) is odd" are true.

** Problem Set 2 - Part 14

Which the following pairs of proposition are equivalent?

(a) \(\neg P \lor Q\), \(P \implies Q\)

(b) \(\neg(P \lor Q))\, \(\neg P \land \neg Q\)

(c) \(\neg P \lor \neg Q\), \(P \lor \neg Q\)

(d) \(\neg(P \and Q)\), \(\neg P \lor Q\)

(e) \(\neg(P \implies (Q \lor R))\), \(\neg(P \implies Q) \lor \neg(P \implies R)\)

(f) \(P \implies (Q \implies R)\), \((P \land Q) \implies R\)

*A*: Let's analyze each pair of propositions to determine if they are logically equivalent:

*(a) \(\neg P \lor Q\), \(P \implies Q\)*

We start with the truth tables for these two proposition:

|---+-----+-----+---------+-------------+------------------+---|
|   | <c> | <c> |   <c>   |     <c>     |       <c>        |   |
|   |  P  |  Q  | \(\neg P\) | \(\neg P \lor Q\) | \(P \implies Q\) |   |
|---+-----+-----+---------+-------------+------------------+---|
| / |  <  |  <  |    <    |      <      |        <         | > |
|   |  T  |  T  |    F    |      T      |        T         |   |
|   |  T  |  F  |    F    |      F      |        F         |   |
|   |  F  |  T  |    T    |      T      |        T         |   |
|   |  F  |  F  |    T    |      T      |        T         |   |
|---+-----+-----+---------+-------------+------------------+---|

From the table, we see that \(\neg P \lor Q\) and \(P \implies Q\) have the same truth values in all cases. Thus, they are
*equivalent*.

*(b) \(\neg(P \lor Q))\, \(\neg P \land \neg Q\)*

|---+-----+-----+-----------+--------------+---------+---------+---------------+---|
|   | <c> | <c> |    <c>    |     <c>      |   <c>   |   <c>   |      <c>      |   |
|   |  P  |  Q  | \(P \lor Q\) | \(\neg(P \lor Q)\) | \(\neg P\) | \(\neg Q\) | \(\neg P \land \neg Q\) |   |
|---+-----+-----+-----------+--------------+---------+---------+---------------+---|
| / |  <  |  <  |     <     |      <       |    <    |    <    |       <       | > |
|   |  T  |  T  |     T     |      F       |    F    |    F    |       F       |   |
|   |  T  |  F  |     T     |      F       |    F    |    T    |       F       |   |
|   |  F  |  T  |     T     |      F       |    T    |    F    |       F       |   |
|   |  F  |  F  |     F     |      T       |    T    |    T    |       T       |   |
|---+-----+-----+-----------+--------------+---------+---------+---------------+---|

Form the table, we see that \(\neg(P \lor Q)\) and \(\neg P \land \neg Q\) have the same truth values in all cases. This, they are
*equivalent*.

*(c) \(\neg P \lor \neg Q\), \(P \lor \neg Q\)*

|---+-----+-----+---------+---------+---------------+------------+---|
|   | <c> | <c> |   <c>   |   <c>   |      <c>      |    <c>     |   |
|   |  P  |  Q  | \(\neg P\) | \(\neg Q\) | \(\neg P \lor \neg Q\) | \(P \lor \neg Q) |   |
|---+-----+-----+---------+---------+---------------+------------+---|
| / |  <  |  <  |    <    |    <    |       <       |     <      | > |
|   |  T  |  T  |    F    |    F    |       F       |     T      |   |
|   |  T  |  F  |    F    |    T    |       T       |     T      |   |
|   |  F  |  T  |    T    |    F    |       T       |     F      |   |
|   |  F  |  F  |    T    |    T    |       T       |     T      |   |
|---+-----+-----+---------+---------+---------------+------------+---|

From the table, we see that \(\neg P \lor \neg Q\) and \(P \lor \neg Q\) do not have the same truth values in all cases. Thus, they are
*not equivalent*.

*(d) \(\neg(P \and Q)\), \(\neg P \lor Q\)*

|---+-----+-----+-----------+--------------+---------+------------+---|
|   | <c> | <c> |    <c>    |     <c>      |   <c>   |    <c>     |   |
|   |  P  |  Q  | \(P \land Q\) | \(\neg(P \land Q)\) | \(\neg P\) | \(\neg P \lor Q) |   |
|---+-----+-----+-----------+--------------+---------+------------+---|
| / |  <  |  <  |     <     |      <       |    <    |     <      | > |
|   |  T  |  T  |     T     |      F       |    F    |     T      |   |
|   |  T  |  F  |     F     |      T       |    F    |     F      |   |
|   |  F  |  T  |     F     |      T       |    T    |     T      |   |
|   |  F  |  F  |     F     |      T       |    T    |     T      |   |
|---+-----+-----+-----------+--------------+---------+------------+---|

From the table, we see that \(\neg(P \land Q)\) and \(\neg P \lor Q\) do not have the same truth values in all cases. Thus, they are
*not equivalent*.

*(e) \(\neg(P \implies (Q \lor R))\), \(\neg(P \implies Q) \lor \neg(P \implies R)\)*

|---+-----+-----+-----+-----------+------------------------+---------------------------+---|
|   | <c> | <c> | <c> |    <c>    |          <c>           |            <c>            |   |
|   |  P  |  Q  |  R  | \(Q \lor R\) | \(P \implies (Q \lor R)\) | \(\neg(P \implies (Q \lor R))\) |   |
|---+-----+-----+-----+-----------+------------------------+---------------------------+---|
| / |  <  |  <  |  <  |     <     |           <            |             <             | > |
|   |  T  |  T  |  T  |     T     |           T            |             F             |   |
|   |  T  |  T  |  F  |     T     |           T            |             F             |   |
|   |  T  |  F  |  T  |     T     |           T            |             F             |   |
|   |  T  |  F  |  F  |     F     |           F            |             T             |   |
|   |  F  |  T  |  T  |     T     |           T            |             F             |   |
|   |  F  |  T  |  F  |     T     |           T            |             F             |   |
|   |  F  |  F  |  T  |     T     |           T            |             F             |   |
|   |  F  |  F  |  F  |     F     |           T            |             F             |   |
|---+-----+-----+-----+-----------+------------------------+---------------------------+---|

|---+------------------+---------------------+------------------+----------------------+---|
|   |       <c>        |         <c>         |       <c>        |         <c>          |   |
|   | \(P \implies Q\) | \(\neg(P \implies Q)\) | \(P \implies R\) | \(\neg (P \implies R)\) |   |
|---+------------------+---------------------+------------------+----------------------+---|
| / |        <         |          <          |        <         |          <           | > |
|   |        T         |          F          |        T         |          F           |   |
|   |        T         |          F          |        F         |          T           |   |
|   |        F         |          T          |        T         |          F           |   |
|   |        F         |          T          |        F         |          T           |   |
|   |        T         |          F          |        T         |          F           |   |
|   |        T         |          F          |        T         |          F           |   |
|   |        T         |          F          |        T         |          F           |   |
|   |        T         |          F          |        T         |          F           |   |
|---+------------------+---------------------+------------------+----------------------+---|

From the table, we see that \(\neg(P \implies (Q \lor R))\) and \(\neg(P \implies Q) \lor \neg(P \implies R)\) have the same truth
values in all cases. Thus, they are *not equivalent*.

*(f) \(P \implies (Q \implies R)\), \((P \land Q) \implies R\)*

|---+-----+-----+-----+------------------+-------------------------------+---|
|   | <c> | <c> | <c> |       <c>        |              <c>              |   |
|   |  P  |  Q  |  R  | \(Q \implies R\) | \(P \implies (Q \implies R)\) |   |
|---+-----+-----+-----+------------------+-------------------------------+---|
| / |  <  |  <  |  <  |        <         |               <               | > |
|   |  T  |  T  |  T  |        T         |               T               |   |
|   |  T  |  T  |  F  |        F         |               F               |   |
|   |  T  |  F  |  T  |        T         |               T               |   |
|   |  T  |  F  |  F  |        T         |               T               |   |
|   |  F  |  T  |  T  |        T         |               T               |   |
|   |  F  |  T  |  F  |        F         |               T               |   |
|   |  F  |  F  |  T  |        T         |               T               |   |
|   |  F  |  F  |  F  |        T         |               T               |   |
|---+-----+-----+-----+------------------+-------------------------------+---|

|---+-----------+------------------------+---|
|   |    <c>    |          <c>           |   |
|   | \(P \land Q\) | \((P \land Q) \implies R\) |   |
|---+-----------+------------------------+---|
| / |     <     |           <            | > |
|   |     T     |           T            |   |
|   |     T     |           F            |   |
|   |     F     |           T            |   |
|   |     F     |           T            |   |
|   |     F     |           T            |   |
|   |     F     |           T            |   |
|   |     F     |           T            |   |
|   |     F     |           T            |   |
|---+-----------+------------------------+---|

From the table, we see that \(P \implies (Q \implies R)\) and \((P \land Q) \implies R\) have the same truth values in all
cases. Thus, they are *equivalent*.

** Problem Set 2 - Part 15

A major focus of this course is learning how to assess mathematical reasoning. How good you are at doing that lies on
sliding scale. Your task is to evaluate the purported (claim to be) proof below, and evaluate it according to the course
rubric. Enter your evaluation (which should be a whole number between 0 and 24, inclusive) in the box. A number within 4
points of the instructor's evaluation cunts as correct. *You should read the article "Using the evaluation rubric" on
the course website (it includes a short explanatory video) before attempt this question*. There will be many more proof
evaluation question like this as the course progress.

[The scoring system somewhat arbitrary, due to limitation platform. But the goal is to provide opportunities for you to
reflect on what makes an argument a good proof, and you are allowed to repeat the Problem Sets as many times as it takes
to be able to progress. Your "scores" is simply feedback information. Moreover, the "passing grade" for Problem Sets is
a low 35%.]

HERE IS WHAT THE INDIVIDUAL SUBMITTED

*Claim*: For any two proposition (P, Q), \(\neg P \land \neg Q\) is equivalent to \(\neg[P \land Q]\).

Proof: Suppose that \(\neg P \land \neg Q\) is true, then booth \(\neg P\) and \(\neg Q\) are true. So \(P\) and \(Q\) are both false.
Thus \(P \land Q\) is false. Hence \(\neg [P \land Q]\) is true. This argument clearly works other way. So we have implication in
both directions, which proves to claim.


* Footnotes

[fn:6] identical in form
[fn:5] a conclusion reached based on evidence and reasoning.
[fn:4] Two statement \(\Phi\) and \(\Psi\) area said to be (logically) equivalent, or just equivalent if each implies the
other we call it the biconditional.
[fn:3] equivalence: a way of defining when two elements are considered equivalent.
[fn:2] axiom: a statement or proposition which is regarded as being established, accepted, or self-evidently true.
[fn:1] implies: strongly suggest the truth or existence of (something not expressly stated).
