#+TITLE: WEEK-II
#+AUTHOR: Agung Tuanany
#+DATE: 2024-06-02 Sun
#+OPTIONS:
#+STARTUP: Course,
#+TAGS: ossu, math-ossu
#+TOC: headlines 2
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \hypersetup{colorlinks=true, linkcolor=blue, urlcolor=cyan, pdfstartview=FitH}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage{ragged2e}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \usepackage{mdframed}
#+LATEX_HEADER: \newenvironment{graypar}{\begin{mdframed}[backgroundcolor=gray!20,hidealllines=true,innertopmargin=10pt,innerbottommargin=10pt,innerrightmargin=10pt,innerleftmargin=20pt,skipabove=10pt,skipbelow=10pt]}{\end{mdframed}}

* Lecture-III: Analysis of Language Implication

Our next step in becoming more precise about our use of language for use in mathematics is to take a close look at the
meaning of the word implies[fn:1].

Most of the benefit from understanding the way our language is used in mathematics comes from trying to figure it out.
The benefit in this case is helping to develop your mathematical thinking ability, and extra process of trying to
understand the issue that goes out for you.

In mathematics we frequently encouter expresion:

\begin{center}
\text{\(\phi\) implies \(\psi\)}
\end{center}

 Indeed, implication is the means by which we prove result in mathematics, starting with observations or axioms[fn:2].
So we'd better understand how the word /implies/ behaves.

In particular, how does the truth or falsity of a statement (\(\phi\) implies \(\psi\)), depend on the truth or falsity
of \(\phi\) and \(\psi\)?

Well, the obvious answer is:

\begin{center}
\text{ The truth of \(\phi\), follows from the truth of \(\psi\)}
\end{center}

Let me give you an example,

# \begin{center}
# \text{ \(\phi: \sqrt{2}\) \hspace{2cm} \($\psi: \( 0 < 1\)}
# \end{center}

# Line 69 (or relevant line number)

\begin{center}
\text{ (\(\phi: \sqrt{2}\)) \hspace{2cm} (\(\psi: (0 < 1)\)}
\end{center}


That \(\phi\) of the statement square root of 2 is a rational; and that \(\psi\) of the statement is 0 less than 1. Let's ask
ourselves, is the statement "\(\phi\) implies \(\psi\)" true?

Well, \(\phi\) is TRUE, and we all know that \(\psi\) is true, cause 0 less than 1. So we have both \(\phi\) and \(\psi\) are truth.

Does that mean "\(\phi\) implies \(\psi\)"? Obviously not. There is no relationship between \(\phi\) and \(\psi\).

The \((\psi: \sqrt{2}\)) is take some effort as you see.

And  \((\psi: ( 0 < 1\)) we all know.

So yes, the truth from first statement (\(\phi\)) doesn't follow from truth of (\(\psi)\).

Now, we realize there's complexity with implication that we didn't meet before when we were dealing with "AND", with
"OR", and with "NOT".

Now we know,

\begin{center}
 {\large\textbf{implication involves causality}}
\end{center}

Causality is an issue of great complexity that philosophers have been discussing for generations.

now we're facing a problem. It didn't arise before, because when we're dealing with conjunction (AND) and disjunction
(OR), it didn't matter whether there was any kind of relationship between the two conjuncts or the two disjuncts.

For example, let's look at the sentence:

\begin{center}
\text{{\textbf{1.}} (Julius Caesar is death) \(\land\) \((1 + 1 = 3)\)}

\text{{\textbf{2.}} (Julius Caesar is death) \(\lor\) \((1 + 1 = 3)\)}
\end{center}

Forming a conjunction and disjunction didn't require any kind of relationship between these two sentences. Clearly,
they're independent. One's statement about a long dead individual, and the other one is a mathematical statement.

Let examine above statements:

- Understanding the conjunction Expression:

   1. (Julius Caesar is death) is TRUE

   2. \((1 + 1 = 3)\): is FALSE

So, the conjunction is FALSE.

- Understanding the disjunction Expression:

   1. (Julius Caesar is death) is TRUE.

   2. \((1 + 1 = 3)\): is FALSE

So, the disjunction is TRUE.

The fact that there's no meaningful relationship between the two conjuncts in the first case, or the two disjuncts in
the second case. Created no lull in determining what the truth value was. It was purely in terms of truth and falsity.

But it's no sitting wit implication, because implication involves /causality/.

So let me just express explicitly,

\begin{center}
\text{implication has a truth part and causation part}
\end{center}

What we're going to do? Ignore the /causation/--part. We're going to leave that to the philosophers if you like, and we're
just going to focus on the /truth/--part.

Throwing away a causation, we can't be left with anything useful, but it turns out, it might seem dangerous thing to do,
to throw away this important causation-part implication, but it turns out when we focus on the truth part we left with
enough to save our leaves in mathematics.

So much that we're going to give (truth part) a name,

\begin{center}
\text{(\uline{Julius Caesar is dead}) \(\land\) \((1 + 1 = 3)\)}
\end{center}

We're going to call it *the conditional* or *material conditional*. That's the part we're going to focus on.

So, we're going to split implication into two part:

\begin{center}
\text{implication = \hspace{0.5cm} conditional \hspace{0.5cm} + \hspace{0.5cm} causation}
\end{center}

The first part, the conditional, we're going to define entirely in terms of /*truth value*/. The second part, we're going
to leave to the philosophers.

The symbol that we use normally for *conditional*, at least the symbol I'm going to use, is:

 \begin{equation}
    \implies
 \end{equation}

So I'm going to write conditional expression like this?

\[
 \phi \implies \psi
\]

That's the truth path of \(\phi\) implies \(\psi\).

When we have a conditional expression like above, we call \(\phi\) /*antecedent*/, and we call \(\psi\) the /*consequent*/; And we
going to formally define the truth of \(\phi\) conditional \(\psi\) in terms of the truth of \(\phi\), and the truth of \(\psi\), we
can write like:

\begin{center}
\text{Define the truth of \(\phi \implies \psi\) in terms of the truth | falsity of \(\phi, \psi\)}
\end{center}

Well, you might worry that by throwing away a /causation/, we're going to be left with a notion that's really of no use
whatsoever. That actually is not the case. Even though we're throwing away something of great significance, hanging on
the truth-part leaves us something very useful.

And the reason is, whenever we have a genuine implication, which are actually the only circumstances in which we're
ultimately going to be interested, whenever we have a genuine implication, the truth behavior of the conditional is the
correct one. It really does capture what happens with truth and falsity, when we have genuine implication, we can write
it down:

\begin{center}
\text{When \(\phi\) \uline{does} implies \(\phi\), \(\phi \implies \psi\) behaves "correctly".}
\end{center}

That probably seems a bit mysterious at this stage, but when we start to look at some examples, I think it should become
clear what I mean.

\begin{center}
\text{The advantage is that the conditional is always defined.}
\end{center}

For real implication, you've got that issue of /causation/. the (\(\phi:\sqrt{2}) (\(\psi > 40\)). If \(\phi\) is true, in other words,
if \(N > 7\), then \(N^2\) is certainly bigger than 40.



[fn:2] axiom: a statement or proposition which is regarded as being established, accepted, or self-evidently true.
[fn:1] implies : strongly suggest the truth or existence of (something not expressly stated).
